// Generated by go-wayland-scanner
// https://github.com/Nomadcxx/sysc-wayland/cmd/sysc-wayland-scanner
// XML file : protocols/tablet-v2.xml
//
// tablet_unstable_v2 Protocol Copyright:
//
// Copyright 2014 © Stephen "Lyude" Chandler Paul
// Copyright 2015-2016 © Red Hat, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation files
// (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software,
// and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice (including the
// next paragraph) shall be included in all copies or substantial
// portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
// BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package cursorshape

import "github.com/Nomadcxx/sysc-wayland/client"

// ZwpTabletManagerV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletManagerV2InterfaceName = "zwp_tablet_manager_v2"

// ZwpTabletManagerV2 : controller object for graphic tablet devices
//
// An object that provides access to the graphics tablets available on this
// system. All tablets are associated with a seat, to get access to the
// actual tablets, use wp_tablet_manager.get_tablet_seat.
type ZwpTabletManagerV2 struct {
	client.BaseProxy
}

// NewZwpTabletManagerV2 : controller object for graphic tablet devices
//
// An object that provides access to the graphics tablets available on this
// system. All tablets are associated with a seat, to get access to the
// actual tablets, use wp_tablet_manager.get_tablet_seat.
func NewZwpTabletManagerV2(ctx *client.Context) *ZwpTabletManagerV2 {
	zwpTabletManagerV2 := &ZwpTabletManagerV2{}
	ctx.Register(zwpTabletManagerV2)
	return zwpTabletManagerV2
}

// GetTabletSeat : get the tablet seat
//
// Get the wp_tablet_seat object for the given seat. This object
// provides access to all graphics tablets in this seat.
//
//	seat: The wl_seat object to retrieve the tablets for
func (i *ZwpTabletManagerV2) GetTabletSeat(seat *client.Seat) (*ZwpTabletSeatV2, error) {
	tabletSeat := NewZwpTabletSeatV2(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], tabletSeat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return tabletSeat, err
}

// Destroy : release the memory for the tablet manager object
//
// Destroy the wp_tablet_manager object. Objects created from this
// object are unaffected and should be destroyed separately.
func (i *ZwpTabletManagerV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletSeatV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletSeatV2InterfaceName = "zwp_tablet_seat_v2"

// ZwpTabletSeatV2 : controller object for graphic tablet devices of a seat
//
// An object that provides access to the graphics tablets available on this
// seat. After binding to this interface, the compositor sends a set of
// wp_tablet_seat.tablet_added and wp_tablet_seat.tool_added events.
type ZwpTabletSeatV2 struct {
	client.BaseProxy
	tabletAddedHandler ZwpTabletSeatV2TabletAddedHandlerFunc
	toolAddedHandler   ZwpTabletSeatV2ToolAddedHandlerFunc
	padAddedHandler    ZwpTabletSeatV2PadAddedHandlerFunc
}

// NewZwpTabletSeatV2 : controller object for graphic tablet devices of a seat
//
// An object that provides access to the graphics tablets available on this
// seat. After binding to this interface, the compositor sends a set of
// wp_tablet_seat.tablet_added and wp_tablet_seat.tool_added events.
func NewZwpTabletSeatV2(ctx *client.Context) *ZwpTabletSeatV2 {
	zwpTabletSeatV2 := &ZwpTabletSeatV2{}
	ctx.Register(zwpTabletSeatV2)
	return zwpTabletSeatV2
}

// Destroy : release the memory for the tablet seat object
//
// Destroy the wp_tablet_seat object. Objects created from this
// object are unaffected and should be destroyed separately.
func (i *ZwpTabletSeatV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletSeatV2TabletAddedEvent : new device notification
//
// This event is sent whenever a new tablet becomes available on this
// seat. This event only provides the object id of the tablet, any
// static information about the tablet (device name, vid/pid, etc.) is
// sent through the wp_tablet interface.
type ZwpTabletSeatV2TabletAddedEvent struct {
	Id *ZwpTabletV2
}
type ZwpTabletSeatV2TabletAddedHandlerFunc func(ZwpTabletSeatV2TabletAddedEvent)

// SetTabletAddedHandler : sets handler for ZwpTabletSeatV2TabletAddedEvent
func (i *ZwpTabletSeatV2) SetTabletAddedHandler(f ZwpTabletSeatV2TabletAddedHandlerFunc) {
	i.tabletAddedHandler = f
}

// ZwpTabletSeatV2ToolAddedEvent : a new tool has been used with a tablet
//
// This event is sent whenever a tool that has not previously been used
// with a tablet comes into use. This event only provides the object id
// of the tool; any static information about the tool (capabilities,
// type, etc.) is sent through the wp_tablet_tool interface.
type ZwpTabletSeatV2ToolAddedEvent struct {
	Id *ZwpTabletToolV2
}
type ZwpTabletSeatV2ToolAddedHandlerFunc func(ZwpTabletSeatV2ToolAddedEvent)

// SetToolAddedHandler : sets handler for ZwpTabletSeatV2ToolAddedEvent
func (i *ZwpTabletSeatV2) SetToolAddedHandler(f ZwpTabletSeatV2ToolAddedHandlerFunc) {
	i.toolAddedHandler = f
}

// ZwpTabletSeatV2PadAddedEvent : new pad notification
//
// This event is sent whenever a new pad is known to the system. Typically,
// pads are physically attached to tablets and a pad_added event is
// sent immediately after the wp_tablet_seat.tablet_added.
// However, some standalone pad devices logically attach to tablets at
// runtime, and the client must wait for wp_tablet_pad.enter to know
// the tablet a pad is attached to.
//
// This event only provides the object id of the pad. All further
// features (buttons, strips, rings) are sent through the wp_tablet_pad
// interface.
type ZwpTabletSeatV2PadAddedEvent struct {
	Id *ZwpTabletPadV2
}
type ZwpTabletSeatV2PadAddedHandlerFunc func(ZwpTabletSeatV2PadAddedEvent)

// SetPadAddedHandler : sets handler for ZwpTabletSeatV2PadAddedEvent
func (i *ZwpTabletSeatV2) SetPadAddedHandler(f ZwpTabletSeatV2PadAddedHandlerFunc) {
	i.padAddedHandler = f
}

func (i *ZwpTabletSeatV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.tabletAddedHandler == nil {
			return
		}
		var e ZwpTabletSeatV2TabletAddedEvent
		l := 0
		idID := client.Uint32(data[l : l+4])
		if id, ok := i.Context().GetProxy(idID).(*ZwpTabletV2); ok && !id.IsZombie() {
			e.Id = id
		} else if idID != 0 {
			id := &ZwpTabletV2{}
			i.Context().RegisterWithID(id, idID)
			e.Id = id
		}
		l += 4

		i.tabletAddedHandler(e)
	case 1:
		if i.toolAddedHandler == nil {
			return
		}
		var e ZwpTabletSeatV2ToolAddedEvent
		l := 0
		idID := client.Uint32(data[l : l+4])
		if id, ok := i.Context().GetProxy(idID).(*ZwpTabletToolV2); ok && !id.IsZombie() {
			e.Id = id
		} else if idID != 0 {
			id := &ZwpTabletToolV2{}
			i.Context().RegisterWithID(id, idID)
			e.Id = id
		}
		l += 4

		i.toolAddedHandler(e)
	case 2:
		if i.padAddedHandler == nil {
			return
		}
		var e ZwpTabletSeatV2PadAddedEvent
		l := 0
		idID := client.Uint32(data[l : l+4])
		if id, ok := i.Context().GetProxy(idID).(*ZwpTabletPadV2); ok && !id.IsZombie() {
			e.Id = id
		} else if idID != 0 {
			id := &ZwpTabletPadV2{}
			i.Context().RegisterWithID(id, idID)
			e.Id = id
		}
		l += 4

		i.padAddedHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ZwpTabletToolV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletToolV2InterfaceName = "zwp_tablet_tool_v2"

// ZwpTabletToolV2 : a physical tablet tool
//
// An object that represents a physical tool that has been, or is
// currently in use with a tablet in this seat. Each wp_tablet_tool
// object stays valid until the client destroys it; the compositor
// reuses the wp_tablet_tool object to indicate that the object's
// respective physical tool has come into proximity of a tablet again.
//
// A wp_tablet_tool object's relation to a physical tool depends on the
// tablet's ability to report serial numbers. If the tablet supports
// this capability, then the object represents a specific physical tool
// and can be identified even when used on multiple tablets.
//
// A tablet tool has a number of static characteristics, e.g. tool type,
// hardware_serial and capabilities. These capabilities are sent in an
// event sequence after the wp_tablet_seat.tool_added event before any
// actual events from this tool. This initial event sequence is
// terminated by a wp_tablet_tool.done event.
//
// Tablet tool events are grouped by wp_tablet_tool.frame events.
// Any events received before a wp_tablet_tool.frame event should be
// considered part of the same hardware state change.
type ZwpTabletToolV2 struct {
	client.BaseProxy
	typeHandler            ZwpTabletToolV2TypeHandlerFunc
	hardwareSerialHandler  ZwpTabletToolV2HardwareSerialHandlerFunc
	hardwareIdWacomHandler ZwpTabletToolV2HardwareIdWacomHandlerFunc
	capabilityHandler      ZwpTabletToolV2CapabilityHandlerFunc
	doneHandler            ZwpTabletToolV2DoneHandlerFunc
	removedHandler         ZwpTabletToolV2RemovedHandlerFunc
	proximityInHandler     ZwpTabletToolV2ProximityInHandlerFunc
	proximityOutHandler    ZwpTabletToolV2ProximityOutHandlerFunc
	downHandler            ZwpTabletToolV2DownHandlerFunc
	upHandler              ZwpTabletToolV2UpHandlerFunc
	motionHandler          ZwpTabletToolV2MotionHandlerFunc
	pressureHandler        ZwpTabletToolV2PressureHandlerFunc
	distanceHandler        ZwpTabletToolV2DistanceHandlerFunc
	tiltHandler            ZwpTabletToolV2TiltHandlerFunc
	rotationHandler        ZwpTabletToolV2RotationHandlerFunc
	sliderHandler          ZwpTabletToolV2SliderHandlerFunc
	wheelHandler           ZwpTabletToolV2WheelHandlerFunc
	buttonHandler          ZwpTabletToolV2ButtonHandlerFunc
	frameHandler           ZwpTabletToolV2FrameHandlerFunc
}

// NewZwpTabletToolV2 : a physical tablet tool
//
// An object that represents a physical tool that has been, or is
// currently in use with a tablet in this seat. Each wp_tablet_tool
// object stays valid until the client destroys it; the compositor
// reuses the wp_tablet_tool object to indicate that the object's
// respective physical tool has come into proximity of a tablet again.
//
// A wp_tablet_tool object's relation to a physical tool depends on the
// tablet's ability to report serial numbers. If the tablet supports
// this capability, then the object represents a specific physical tool
// and can be identified even when used on multiple tablets.
//
// A tablet tool has a number of static characteristics, e.g. tool type,
// hardware_serial and capabilities. These capabilities are sent in an
// event sequence after the wp_tablet_seat.tool_added event before any
// actual events from this tool. This initial event sequence is
// terminated by a wp_tablet_tool.done event.
//
// Tablet tool events are grouped by wp_tablet_tool.frame events.
// Any events received before a wp_tablet_tool.frame event should be
// considered part of the same hardware state change.
func NewZwpTabletToolV2(ctx *client.Context) *ZwpTabletToolV2 {
	zwpTabletToolV2 := &ZwpTabletToolV2{}
	ctx.Register(zwpTabletToolV2)
	return zwpTabletToolV2
}

// SetCursor : set the tablet tool's surface
//
// Sets the surface of the cursor used for this tool on the given
// tablet. This request only takes effect if the tool is in proximity
// of one of the requesting client's surfaces or the surface parameter
// is the current pointer surface. If there was a previous surface set
// with this request it is replaced. If surface is NULL, the cursor
// image is hidden.
//
// The parameters hotspot_x and hotspot_y define the position of the
// pointer surface relative to the pointer location. Its top-left corner
// is always at (x, y) - (hotspot_x, hotspot_y), where (x, y) are the
// coordinates of the pointer location, in surface-local coordinates.
//
// On surface.attach requests to the pointer surface, hotspot_x and
// hotspot_y are decremented by the x and y parameters passed to the
// request. Attach must be confirmed by wl_surface.commit as usual.
//
// The hotspot can also be updated by passing the currently set pointer
// surface to this request with new values for hotspot_x and hotspot_y.
//
// The current and pending input regions of the wl_surface are cleared,
// and wl_surface.set_input_region is ignored until the wl_surface is no
// longer used as the cursor. When the use as a cursor ends, the current
// and pending input regions become undefined, and the wl_surface is
// unmapped.
//
// This request gives the surface the role of a wp_tablet_tool cursor. A
// surface may only ever be used as the cursor surface for one
// wp_tablet_tool. If the surface already has another role or has
// previously been used as cursor surface for a different tool, a
// protocol error is raised.
//
//	serial: serial of the proximity_in event
//	hotspotX: surface-local x coordinate
//	hotspotY: surface-local y coordinate
func (i *ZwpTabletToolV2) SetCursor(serial uint32, surface *client.Surface, hotspotX, hotspotY int32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	if surface == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], surface.ID())
		l += 4
	}
	client.PutUint32(_reqBuf[l:l+4], uint32(hotspotX))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(hotspotY))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : destroy the tool object
//
// This destroys the client's resource for this tool object.
func (i *ZwpTabletToolV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ZwpTabletToolV2Type uint32

// ZwpTabletToolV2Type : a physical tool type
//
// Describes the physical type of a tool. The physical type of a tool
// generally defines its base usage.
//
// The mouse tool represents a mouse-shaped tool that is not a relative
// device but bound to the tablet's surface, providing absolute
// coordinates.
//
// The lens tool is a mouse-shaped tool with an attached lens to
// provide precision focus.
const (
	// ZwpTabletToolV2TypePen : Pen
	ZwpTabletToolV2TypePen ZwpTabletToolV2Type = 0x140
	// ZwpTabletToolV2TypeEraser : Eraser
	ZwpTabletToolV2TypeEraser ZwpTabletToolV2Type = 0x141
	// ZwpTabletToolV2TypeBrush : Brush
	ZwpTabletToolV2TypeBrush ZwpTabletToolV2Type = 0x142
	// ZwpTabletToolV2TypePencil : Pencil
	ZwpTabletToolV2TypePencil ZwpTabletToolV2Type = 0x143
	// ZwpTabletToolV2TypeAirbrush : Airbrush
	ZwpTabletToolV2TypeAirbrush ZwpTabletToolV2Type = 0x144
	// ZwpTabletToolV2TypeFinger : Finger
	ZwpTabletToolV2TypeFinger ZwpTabletToolV2Type = 0x145
	// ZwpTabletToolV2TypeMouse : Mouse
	ZwpTabletToolV2TypeMouse ZwpTabletToolV2Type = 0x146
	// ZwpTabletToolV2TypeLens : Lens
	ZwpTabletToolV2TypeLens ZwpTabletToolV2Type = 0x147
)

func (e ZwpTabletToolV2Type) Name() string {
	switch e {
	case ZwpTabletToolV2TypePen:
		return "pen"
	case ZwpTabletToolV2TypeEraser:
		return "eraser"
	case ZwpTabletToolV2TypeBrush:
		return "brush"
	case ZwpTabletToolV2TypePencil:
		return "pencil"
	case ZwpTabletToolV2TypeAirbrush:
		return "airbrush"
	case ZwpTabletToolV2TypeFinger:
		return "finger"
	case ZwpTabletToolV2TypeMouse:
		return "mouse"
	case ZwpTabletToolV2TypeLens:
		return "lens"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2Type) Value() string {
	switch e {
	case ZwpTabletToolV2TypePen:
		return "0x140"
	case ZwpTabletToolV2TypeEraser:
		return "0x141"
	case ZwpTabletToolV2TypeBrush:
		return "0x142"
	case ZwpTabletToolV2TypePencil:
		return "0x143"
	case ZwpTabletToolV2TypeAirbrush:
		return "0x144"
	case ZwpTabletToolV2TypeFinger:
		return "0x145"
	case ZwpTabletToolV2TypeMouse:
		return "0x146"
	case ZwpTabletToolV2TypeLens:
		return "0x147"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2Type) String() string {
	return e.Name() + "=" + e.Value()
}

type ZwpTabletToolV2Capability uint32

// ZwpTabletToolV2Capability : capability flags for a tool
//
// Describes extra capabilities on a tablet.
//
// Any tool must provide x and y values, extra axes are
// device-specific.
const (
	// ZwpTabletToolV2CapabilityTilt : Tilt axes
	ZwpTabletToolV2CapabilityTilt ZwpTabletToolV2Capability = 1
	// ZwpTabletToolV2CapabilityPressure : Pressure axis
	ZwpTabletToolV2CapabilityPressure ZwpTabletToolV2Capability = 2
	// ZwpTabletToolV2CapabilityDistance : Distance axis
	ZwpTabletToolV2CapabilityDistance ZwpTabletToolV2Capability = 3
	// ZwpTabletToolV2CapabilityRotation : Z-rotation axis
	ZwpTabletToolV2CapabilityRotation ZwpTabletToolV2Capability = 4
	// ZwpTabletToolV2CapabilitySlider : Slider axis
	ZwpTabletToolV2CapabilitySlider ZwpTabletToolV2Capability = 5
	// ZwpTabletToolV2CapabilityWheel : Wheel axis
	ZwpTabletToolV2CapabilityWheel ZwpTabletToolV2Capability = 6
)

func (e ZwpTabletToolV2Capability) Name() string {
	switch e {
	case ZwpTabletToolV2CapabilityTilt:
		return "tilt"
	case ZwpTabletToolV2CapabilityPressure:
		return "pressure"
	case ZwpTabletToolV2CapabilityDistance:
		return "distance"
	case ZwpTabletToolV2CapabilityRotation:
		return "rotation"
	case ZwpTabletToolV2CapabilitySlider:
		return "slider"
	case ZwpTabletToolV2CapabilityWheel:
		return "wheel"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2Capability) Value() string {
	switch e {
	case ZwpTabletToolV2CapabilityTilt:
		return "1"
	case ZwpTabletToolV2CapabilityPressure:
		return "2"
	case ZwpTabletToolV2CapabilityDistance:
		return "3"
	case ZwpTabletToolV2CapabilityRotation:
		return "4"
	case ZwpTabletToolV2CapabilitySlider:
		return "5"
	case ZwpTabletToolV2CapabilityWheel:
		return "6"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2Capability) String() string {
	return e.Name() + "=" + e.Value()
}

type ZwpTabletToolV2ButtonState uint32

// ZwpTabletToolV2ButtonState : physical button state
//
// Describes the physical state of a button that produced the button event.
const (
	// ZwpTabletToolV2ButtonStateReleased : button is not pressed
	ZwpTabletToolV2ButtonStateReleased ZwpTabletToolV2ButtonState = 0
	// ZwpTabletToolV2ButtonStatePressed : button is pressed
	ZwpTabletToolV2ButtonStatePressed ZwpTabletToolV2ButtonState = 1
)

func (e ZwpTabletToolV2ButtonState) Name() string {
	switch e {
	case ZwpTabletToolV2ButtonStateReleased:
		return "released"
	case ZwpTabletToolV2ButtonStatePressed:
		return "pressed"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2ButtonState) Value() string {
	switch e {
	case ZwpTabletToolV2ButtonStateReleased:
		return "0"
	case ZwpTabletToolV2ButtonStatePressed:
		return "1"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2ButtonState) String() string {
	return e.Name() + "=" + e.Value()
}

type ZwpTabletToolV2Error uint32

// ZwpTabletToolV2Error :
const (
	// ZwpTabletToolV2ErrorRole : given wl_surface has another role
	ZwpTabletToolV2ErrorRole ZwpTabletToolV2Error = 0
)

func (e ZwpTabletToolV2Error) Name() string {
	switch e {
	case ZwpTabletToolV2ErrorRole:
		return "role"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2Error) Value() string {
	switch e {
	case ZwpTabletToolV2ErrorRole:
		return "0"
	default:
		return ""
	}
}

func (e ZwpTabletToolV2Error) String() string {
	return e.Name() + "=" + e.Value()
}

// ZwpTabletToolV2TypeEvent : tool type
//
// The tool type is the high-level type of the tool and usually decides
// the interaction expected from this tool.
//
// This event is sent in the initial burst of events before the
// wp_tablet_tool.done event.
type ZwpTabletToolV2TypeEvent struct {
	ToolType uint32
}
type ZwpTabletToolV2TypeHandlerFunc func(ZwpTabletToolV2TypeEvent)

// SetTypeHandler : sets handler for ZwpTabletToolV2TypeEvent
func (i *ZwpTabletToolV2) SetTypeHandler(f ZwpTabletToolV2TypeHandlerFunc) {
	i.typeHandler = f
}

// ZwpTabletToolV2HardwareSerialEvent : unique hardware serial number of the tool
//
// If the physical tool can be identified by a unique 64-bit serial
// number, this event notifies the client of this serial number.
//
// If multiple tablets are available in the same seat and the tool is
// uniquely identifiable by the serial number, that tool may move
// between tablets.
//
// Otherwise, if the tool has no serial number and this event is
// missing, the tool is tied to the tablet it first comes into
// proximity with. Even if the physical tool is used on multiple
// tablets, separate wp_tablet_tool objects will be created, one per
// tablet.
//
// This event is sent in the initial burst of events before the
// wp_tablet_tool.done event.
type ZwpTabletToolV2HardwareSerialEvent struct {
	HardwareSerialHi uint32
	HardwareSerialLo uint32
}
type ZwpTabletToolV2HardwareSerialHandlerFunc func(ZwpTabletToolV2HardwareSerialEvent)

// SetHardwareSerialHandler : sets handler for ZwpTabletToolV2HardwareSerialEvent
func (i *ZwpTabletToolV2) SetHardwareSerialHandler(f ZwpTabletToolV2HardwareSerialHandlerFunc) {
	i.hardwareSerialHandler = f
}

// ZwpTabletToolV2HardwareIdWacomEvent : hardware id notification in Wacom's format
//
// This event notifies the client of a hardware id available on this tool.
//
// The hardware id is a device-specific 64-bit id that provides extra
// information about the tool in use, beyond the wl_tool.type
// enumeration. The format of the id is specific to tablets made by
// Wacom Inc. For example, the hardware id of a Wacom Grip
// Pen (a stylus) is 0x802.
//
// This event is sent in the initial burst of events before the
// wp_tablet_tool.done event.
type ZwpTabletToolV2HardwareIdWacomEvent struct {
	HardwareIdHi uint32
	HardwareIdLo uint32
}
type ZwpTabletToolV2HardwareIdWacomHandlerFunc func(ZwpTabletToolV2HardwareIdWacomEvent)

// SetHardwareIdWacomHandler : sets handler for ZwpTabletToolV2HardwareIdWacomEvent
func (i *ZwpTabletToolV2) SetHardwareIdWacomHandler(f ZwpTabletToolV2HardwareIdWacomHandlerFunc) {
	i.hardwareIdWacomHandler = f
}

// ZwpTabletToolV2CapabilityEvent : tool capability notification
//
// This event notifies the client of any capabilities of this tool,
// beyond the main set of x/y axes and tip up/down detection.
//
// One event is sent for each extra capability available on this tool.
//
// This event is sent in the initial burst of events before the
// wp_tablet_tool.done event.
type ZwpTabletToolV2CapabilityEvent struct {
	Capability uint32
}
type ZwpTabletToolV2CapabilityHandlerFunc func(ZwpTabletToolV2CapabilityEvent)

// SetCapabilityHandler : sets handler for ZwpTabletToolV2CapabilityEvent
func (i *ZwpTabletToolV2) SetCapabilityHandler(f ZwpTabletToolV2CapabilityHandlerFunc) {
	i.capabilityHandler = f
}

// ZwpTabletToolV2DoneEvent : tool description events sequence complete
//
// This event signals the end of the initial burst of descriptive
// events. A client may consider the static description of the tool to
// be complete and finalize initialization of the tool.
type ZwpTabletToolV2DoneEvent struct{}
type ZwpTabletToolV2DoneHandlerFunc func(ZwpTabletToolV2DoneEvent)

// SetDoneHandler : sets handler for ZwpTabletToolV2DoneEvent
func (i *ZwpTabletToolV2) SetDoneHandler(f ZwpTabletToolV2DoneHandlerFunc) {
	i.doneHandler = f
}

// ZwpTabletToolV2RemovedEvent : tool removed
//
// This event is sent when the tool is removed from the system and will
// send no further events. Should the physical tool come back into
// proximity later, a new wp_tablet_tool object will be created.
//
// It is compositor-dependent when a tool is removed. A compositor may
// remove a tool on proximity out, tablet removal or any other reason.
// A compositor may also keep a tool alive until shutdown.
//
// If the tool is currently in proximity, a proximity_out event will be
// sent before the removed event. See wp_tablet_tool.proximity_out for
// the handling of any buttons logically down.
//
// When this event is received, the client must wp_tablet_tool.destroy
// the object.
type ZwpTabletToolV2RemovedEvent struct{}
type ZwpTabletToolV2RemovedHandlerFunc func(ZwpTabletToolV2RemovedEvent)

// SetRemovedHandler : sets handler for ZwpTabletToolV2RemovedEvent
func (i *ZwpTabletToolV2) SetRemovedHandler(f ZwpTabletToolV2RemovedHandlerFunc) {
	i.removedHandler = f
}

// ZwpTabletToolV2ProximityInEvent : proximity in event
//
// Notification that this tool is focused on a certain surface.
//
// This event can be received when the tool has moved from one surface to
// another, or when the tool has come back into proximity above the
// surface.
//
// If any button is logically down when the tool comes into proximity,
// the respective button event is sent after the proximity_in event but
// within the same frame as the proximity_in event.
type ZwpTabletToolV2ProximityInEvent struct {
	Serial  uint32
	Tablet  *ZwpTabletV2
	Surface *client.Surface
}
type ZwpTabletToolV2ProximityInHandlerFunc func(ZwpTabletToolV2ProximityInEvent)

// SetProximityInHandler : sets handler for ZwpTabletToolV2ProximityInEvent
func (i *ZwpTabletToolV2) SetProximityInHandler(f ZwpTabletToolV2ProximityInHandlerFunc) {
	i.proximityInHandler = f
}

// ZwpTabletToolV2ProximityOutEvent : proximity out event
//
// Notification that this tool has either left proximity, or is no
// longer focused on a certain surface.
//
// When the tablet tool leaves proximity of the tablet, button release
// events are sent for each button that was held down at the time of
// leaving proximity. These events are sent before the proximity_out
// event but within the same wp_tablet.frame.
//
// If the tool stays within proximity of the tablet, but the focus
// changes from one surface to another, a button release event may not
// be sent until the button is actually released or the tool leaves the
// proximity of the tablet.
type ZwpTabletToolV2ProximityOutEvent struct{}
type ZwpTabletToolV2ProximityOutHandlerFunc func(ZwpTabletToolV2ProximityOutEvent)

// SetProximityOutHandler : sets handler for ZwpTabletToolV2ProximityOutEvent
func (i *ZwpTabletToolV2) SetProximityOutHandler(f ZwpTabletToolV2ProximityOutHandlerFunc) {
	i.proximityOutHandler = f
}

// ZwpTabletToolV2DownEvent : tablet tool is making contact
//
// Sent whenever the tablet tool comes in contact with the surface of the
// tablet.
//
// If the tool is already in contact with the tablet when entering the
// input region, the client owning said region will receive a
// wp_tablet.proximity_in event, followed by a wp_tablet.down
// event and a wp_tablet.frame event.
//
// Note that this event describes logical contact, not physical
// contact. On some devices, a compositor may not consider a tool in
// logical contact until a minimum physical pressure threshold is
// exceeded.
type ZwpTabletToolV2DownEvent struct {
	Serial uint32
}
type ZwpTabletToolV2DownHandlerFunc func(ZwpTabletToolV2DownEvent)

// SetDownHandler : sets handler for ZwpTabletToolV2DownEvent
func (i *ZwpTabletToolV2) SetDownHandler(f ZwpTabletToolV2DownHandlerFunc) {
	i.downHandler = f
}

// ZwpTabletToolV2UpEvent : tablet tool is no longer making contact
//
// Sent whenever the tablet tool stops making contact with the surface of
// the tablet, or when the tablet tool moves out of the input region
// and the compositor grab (if any) is dismissed.
//
// If the tablet tool moves out of the input region while in contact
// with the surface of the tablet and the compositor does not have an
// ongoing grab on the surface, the client owning said region will
// receive a wp_tablet.up event, followed by a wp_tablet.proximity_out
// event and a wp_tablet.frame event. If the compositor has an ongoing
// grab on this device, this event sequence is sent whenever the grab
// is dismissed in the future.
//
// Note that this event describes logical contact, not physical
// contact. On some devices, a compositor may not consider a tool out
// of logical contact until physical pressure falls below a specific
// threshold.
type ZwpTabletToolV2UpEvent struct{}
type ZwpTabletToolV2UpHandlerFunc func(ZwpTabletToolV2UpEvent)

// SetUpHandler : sets handler for ZwpTabletToolV2UpEvent
func (i *ZwpTabletToolV2) SetUpHandler(f ZwpTabletToolV2UpHandlerFunc) {
	i.upHandler = f
}

// ZwpTabletToolV2MotionEvent : motion event
//
// Sent whenever a tablet tool moves.
type ZwpTabletToolV2MotionEvent struct {
	X float64
	Y float64
}
type ZwpTabletToolV2MotionHandlerFunc func(ZwpTabletToolV2MotionEvent)

// SetMotionHandler : sets handler for ZwpTabletToolV2MotionEvent
func (i *ZwpTabletToolV2) SetMotionHandler(f ZwpTabletToolV2MotionHandlerFunc) {
	i.motionHandler = f
}

// ZwpTabletToolV2PressureEvent : pressure change event
//
// Sent whenever the pressure axis on a tool changes. The value of this
// event is normalized to a value between 0 and 65535.
//
// Note that pressure may be nonzero even when a tool is not in logical
// contact. See the down and up events for more details.
type ZwpTabletToolV2PressureEvent struct {
	Pressure uint32
}
type ZwpTabletToolV2PressureHandlerFunc func(ZwpTabletToolV2PressureEvent)

// SetPressureHandler : sets handler for ZwpTabletToolV2PressureEvent
func (i *ZwpTabletToolV2) SetPressureHandler(f ZwpTabletToolV2PressureHandlerFunc) {
	i.pressureHandler = f
}

// ZwpTabletToolV2DistanceEvent : distance change event
//
// Sent whenever the distance axis on a tool changes. The value of this
// event is normalized to a value between 0 and 65535.
//
// Note that distance may be nonzero even when a tool is not in logical
// contact. See the down and up events for more details.
type ZwpTabletToolV2DistanceEvent struct {
	Distance uint32
}
type ZwpTabletToolV2DistanceHandlerFunc func(ZwpTabletToolV2DistanceEvent)

// SetDistanceHandler : sets handler for ZwpTabletToolV2DistanceEvent
func (i *ZwpTabletToolV2) SetDistanceHandler(f ZwpTabletToolV2DistanceHandlerFunc) {
	i.distanceHandler = f
}

// ZwpTabletToolV2TiltEvent : tilt change event
//
// Sent whenever one or both of the tilt axes on a tool change. Each tilt
// value is in degrees, relative to the z-axis of the tablet.
// The angle is positive when the top of a tool tilts along the
// positive x or y axis.
type ZwpTabletToolV2TiltEvent struct {
	TiltX float64
	TiltY float64
}
type ZwpTabletToolV2TiltHandlerFunc func(ZwpTabletToolV2TiltEvent)

// SetTiltHandler : sets handler for ZwpTabletToolV2TiltEvent
func (i *ZwpTabletToolV2) SetTiltHandler(f ZwpTabletToolV2TiltHandlerFunc) {
	i.tiltHandler = f
}

// ZwpTabletToolV2RotationEvent : z-rotation change event
//
// Sent whenever the z-rotation axis on the tool changes. The
// rotation value is in degrees clockwise from the tool's
// logical neutral position.
type ZwpTabletToolV2RotationEvent struct {
	Degrees float64
}
type ZwpTabletToolV2RotationHandlerFunc func(ZwpTabletToolV2RotationEvent)

// SetRotationHandler : sets handler for ZwpTabletToolV2RotationEvent
func (i *ZwpTabletToolV2) SetRotationHandler(f ZwpTabletToolV2RotationHandlerFunc) {
	i.rotationHandler = f
}

// ZwpTabletToolV2SliderEvent : Slider position change event
//
// Sent whenever the slider position on the tool changes. The
// value is normalized between -65535 and 65535, with 0 as the logical
// neutral position of the slider.
//
// The slider is available on e.g. the Wacom Airbrush tool.
type ZwpTabletToolV2SliderEvent struct {
	Position int32
}
type ZwpTabletToolV2SliderHandlerFunc func(ZwpTabletToolV2SliderEvent)

// SetSliderHandler : sets handler for ZwpTabletToolV2SliderEvent
func (i *ZwpTabletToolV2) SetSliderHandler(f ZwpTabletToolV2SliderHandlerFunc) {
	i.sliderHandler = f
}

// ZwpTabletToolV2WheelEvent : Wheel delta event
//
// Sent whenever the wheel on the tool emits an event. This event
// contains two values for the same axis change. The degrees value is
// in the same orientation as the wl_pointer.vertical_scroll axis. The
// clicks value is in discrete logical clicks of the mouse wheel. This
// value may be zero if the movement of the wheel was less
// than one logical click.
//
// Clients should choose either value and avoid mixing degrees and
// clicks. The compositor may accumulate values smaller than a logical
// click and emulate click events when a certain threshold is met.
// Thus, wl_tablet_tool.wheel events with non-zero clicks values may
// have different degrees values.
type ZwpTabletToolV2WheelEvent struct {
	Degrees float64
	Clicks  int32
}
type ZwpTabletToolV2WheelHandlerFunc func(ZwpTabletToolV2WheelEvent)

// SetWheelHandler : sets handler for ZwpTabletToolV2WheelEvent
func (i *ZwpTabletToolV2) SetWheelHandler(f ZwpTabletToolV2WheelHandlerFunc) {
	i.wheelHandler = f
}

// ZwpTabletToolV2ButtonEvent : button event
//
// Sent whenever a button on the tool is pressed or released.
//
// If a button is held down when the tool moves in or out of proximity,
// button events are generated by the compositor. See
// wp_tablet_tool.proximity_in and wp_tablet_tool.proximity_out for
// details.
type ZwpTabletToolV2ButtonEvent struct {
	Serial uint32
	Button uint32
	State  uint32
}
type ZwpTabletToolV2ButtonHandlerFunc func(ZwpTabletToolV2ButtonEvent)

// SetButtonHandler : sets handler for ZwpTabletToolV2ButtonEvent
func (i *ZwpTabletToolV2) SetButtonHandler(f ZwpTabletToolV2ButtonHandlerFunc) {
	i.buttonHandler = f
}

// ZwpTabletToolV2FrameEvent : frame event
//
// Marks the end of a series of axis and/or button updates from the
// tablet. The Wayland protocol requires axis updates to be sent
// sequentially, however all events within a frame should be considered
// one hardware event.
type ZwpTabletToolV2FrameEvent struct {
	Time uint32
}
type ZwpTabletToolV2FrameHandlerFunc func(ZwpTabletToolV2FrameEvent)

// SetFrameHandler : sets handler for ZwpTabletToolV2FrameEvent
func (i *ZwpTabletToolV2) SetFrameHandler(f ZwpTabletToolV2FrameHandlerFunc) {
	i.frameHandler = f
}

func (i *ZwpTabletToolV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.typeHandler == nil {
			return
		}
		var e ZwpTabletToolV2TypeEvent
		l := 0
		e.ToolType = client.Uint32(data[l : l+4])
		l += 4

		i.typeHandler(e)
	case 1:
		if i.hardwareSerialHandler == nil {
			return
		}
		var e ZwpTabletToolV2HardwareSerialEvent
		l := 0
		e.HardwareSerialHi = client.Uint32(data[l : l+4])
		l += 4
		e.HardwareSerialLo = client.Uint32(data[l : l+4])
		l += 4

		i.hardwareSerialHandler(e)
	case 2:
		if i.hardwareIdWacomHandler == nil {
			return
		}
		var e ZwpTabletToolV2HardwareIdWacomEvent
		l := 0
		e.HardwareIdHi = client.Uint32(data[l : l+4])
		l += 4
		e.HardwareIdLo = client.Uint32(data[l : l+4])
		l += 4

		i.hardwareIdWacomHandler(e)
	case 3:
		if i.capabilityHandler == nil {
			return
		}
		var e ZwpTabletToolV2CapabilityEvent
		l := 0
		e.Capability = client.Uint32(data[l : l+4])
		l += 4

		i.capabilityHandler(e)
	case 4:
		if i.doneHandler == nil {
			return
		}
		var e ZwpTabletToolV2DoneEvent

		i.doneHandler(e)
	case 5:
		if i.removedHandler == nil {
			return
		}
		var e ZwpTabletToolV2RemovedEvent

		i.removedHandler(e)
	case 6:
		if i.proximityInHandler == nil {
			return
		}
		var e ZwpTabletToolV2ProximityInEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4
		tabletID := client.Uint32(data[l : l+4])
		if tablet, ok := i.Context().GetProxy(tabletID).(*ZwpTabletV2); ok && !tablet.IsZombie() {
			e.Tablet = tablet
		} else {
			e.Tablet = nil
		}
		l += 4
		surfaceID := client.Uint32(data[l : l+4])
		if surface, ok := i.Context().GetProxy(surfaceID).(*client.Surface); ok && !surface.IsZombie() {
			e.Surface = surface
		} else {
			e.Surface = nil
		}
		l += 4

		i.proximityInHandler(e)
	case 7:
		if i.proximityOutHandler == nil {
			return
		}
		var e ZwpTabletToolV2ProximityOutEvent

		i.proximityOutHandler(e)
	case 8:
		if i.downHandler == nil {
			return
		}
		var e ZwpTabletToolV2DownEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4

		i.downHandler(e)
	case 9:
		if i.upHandler == nil {
			return
		}
		var e ZwpTabletToolV2UpEvent

		i.upHandler(e)
	case 10:
		if i.motionHandler == nil {
			return
		}
		var e ZwpTabletToolV2MotionEvent
		l := 0
		e.X = client.Fixed(data[l : l+4])
		l += 4
		e.Y = client.Fixed(data[l : l+4])
		l += 4

		i.motionHandler(e)
	case 11:
		if i.pressureHandler == nil {
			return
		}
		var e ZwpTabletToolV2PressureEvent
		l := 0
		e.Pressure = client.Uint32(data[l : l+4])
		l += 4

		i.pressureHandler(e)
	case 12:
		if i.distanceHandler == nil {
			return
		}
		var e ZwpTabletToolV2DistanceEvent
		l := 0
		e.Distance = client.Uint32(data[l : l+4])
		l += 4

		i.distanceHandler(e)
	case 13:
		if i.tiltHandler == nil {
			return
		}
		var e ZwpTabletToolV2TiltEvent
		l := 0
		e.TiltX = client.Fixed(data[l : l+4])
		l += 4
		e.TiltY = client.Fixed(data[l : l+4])
		l += 4

		i.tiltHandler(e)
	case 14:
		if i.rotationHandler == nil {
			return
		}
		var e ZwpTabletToolV2RotationEvent
		l := 0
		e.Degrees = client.Fixed(data[l : l+4])
		l += 4

		i.rotationHandler(e)
	case 15:
		if i.sliderHandler == nil {
			return
		}
		var e ZwpTabletToolV2SliderEvent
		l := 0
		e.Position = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.sliderHandler(e)
	case 16:
		if i.wheelHandler == nil {
			return
		}
		var e ZwpTabletToolV2WheelEvent
		l := 0
		e.Degrees = client.Fixed(data[l : l+4])
		l += 4
		e.Clicks = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.wheelHandler(e)
	case 17:
		if i.buttonHandler == nil {
			return
		}
		var e ZwpTabletToolV2ButtonEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4
		e.Button = client.Uint32(data[l : l+4])
		l += 4
		e.State = client.Uint32(data[l : l+4])
		l += 4

		i.buttonHandler(e)
	case 18:
		if i.frameHandler == nil {
			return
		}
		var e ZwpTabletToolV2FrameEvent
		l := 0
		e.Time = client.Uint32(data[l : l+4])
		l += 4

		i.frameHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ZwpTabletV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletV2InterfaceName = "zwp_tablet_v2"

// ZwpTabletV2 : graphics tablet device
//
// The wp_tablet interface represents one graphics tablet device. The
// tablet interface itself does not generate events; all events are
// generated by wp_tablet_tool objects when in proximity above a tablet.
//
// A tablet has a number of static characteristics, e.g. device name and
// pid/vid. These capabilities are sent in an event sequence after the
// wp_tablet_seat.tablet_added event. This initial event sequence is
// terminated by a wp_tablet.done event.
type ZwpTabletV2 struct {
	client.BaseProxy
	nameHandler    ZwpTabletV2NameHandlerFunc
	idHandler      ZwpTabletV2IdHandlerFunc
	pathHandler    ZwpTabletV2PathHandlerFunc
	doneHandler    ZwpTabletV2DoneHandlerFunc
	removedHandler ZwpTabletV2RemovedHandlerFunc
}

// NewZwpTabletV2 : graphics tablet device
//
// The wp_tablet interface represents one graphics tablet device. The
// tablet interface itself does not generate events; all events are
// generated by wp_tablet_tool objects when in proximity above a tablet.
//
// A tablet has a number of static characteristics, e.g. device name and
// pid/vid. These capabilities are sent in an event sequence after the
// wp_tablet_seat.tablet_added event. This initial event sequence is
// terminated by a wp_tablet.done event.
func NewZwpTabletV2(ctx *client.Context) *ZwpTabletV2 {
	zwpTabletV2 := &ZwpTabletV2{}
	ctx.Register(zwpTabletV2)
	return zwpTabletV2
}

// Destroy : destroy the tablet object
//
// This destroys the client's resource for this tablet object.
func (i *ZwpTabletV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletV2NameEvent : tablet device name
//
// A descriptive name for the tablet device.
//
// If the device has no descriptive name, this event is not sent.
//
// This event is sent in the initial burst of events before the
// wp_tablet.done event.
type ZwpTabletV2NameEvent struct {
	Name string
}
type ZwpTabletV2NameHandlerFunc func(ZwpTabletV2NameEvent)

// SetNameHandler : sets handler for ZwpTabletV2NameEvent
func (i *ZwpTabletV2) SetNameHandler(f ZwpTabletV2NameHandlerFunc) {
	i.nameHandler = f
}

// ZwpTabletV2IdEvent : tablet device USB vendor/product id
//
// The USB vendor and product IDs for the tablet device.
//
// If the device has no USB vendor/product ID, this event is not sent.
// This can happen for virtual devices or non-USB devices, for instance.
//
// This event is sent in the initial burst of events before the
// wp_tablet.done event.
type ZwpTabletV2IdEvent struct {
	Vid uint32
	Pid uint32
}
type ZwpTabletV2IdHandlerFunc func(ZwpTabletV2IdEvent)

// SetIdHandler : sets handler for ZwpTabletV2IdEvent
func (i *ZwpTabletV2) SetIdHandler(f ZwpTabletV2IdHandlerFunc) {
	i.idHandler = f
}

// ZwpTabletV2PathEvent : path to the device
//
// A system-specific device path that indicates which device is behind
// this wp_tablet. This information may be used to gather additional
// information about the device, e.g. through libwacom.
//
// A device may have more than one device path. If so, multiple
// wp_tablet.path events are sent. A device may be emulated and not
// have a device path, and in that case this event will not be sent.
//
// The format of the path is unspecified, it may be a device node, a
// sysfs path, or some other identifier. It is up to the client to
// identify the string provided.
//
// This event is sent in the initial burst of events before the
// wp_tablet.done event.
type ZwpTabletV2PathEvent struct {
	Path string
}
type ZwpTabletV2PathHandlerFunc func(ZwpTabletV2PathEvent)

// SetPathHandler : sets handler for ZwpTabletV2PathEvent
func (i *ZwpTabletV2) SetPathHandler(f ZwpTabletV2PathHandlerFunc) {
	i.pathHandler = f
}

// ZwpTabletV2DoneEvent : tablet description events sequence complete
//
// This event is sent immediately to signal the end of the initial
// burst of descriptive events. A client may consider the static
// description of the tablet to be complete and finalize initialization
// of the tablet.
type ZwpTabletV2DoneEvent struct{}
type ZwpTabletV2DoneHandlerFunc func(ZwpTabletV2DoneEvent)

// SetDoneHandler : sets handler for ZwpTabletV2DoneEvent
func (i *ZwpTabletV2) SetDoneHandler(f ZwpTabletV2DoneHandlerFunc) {
	i.doneHandler = f
}

// ZwpTabletV2RemovedEvent : tablet removed event
//
// Sent when the tablet has been removed from the system. When a tablet
// is removed, some tools may be removed.
//
// When this event is received, the client must wp_tablet.destroy
// the object.
type ZwpTabletV2RemovedEvent struct{}
type ZwpTabletV2RemovedHandlerFunc func(ZwpTabletV2RemovedEvent)

// SetRemovedHandler : sets handler for ZwpTabletV2RemovedEvent
func (i *ZwpTabletV2) SetRemovedHandler(f ZwpTabletV2RemovedHandlerFunc) {
	i.removedHandler = f
}

func (i *ZwpTabletV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.nameHandler == nil {
			return
		}
		var e ZwpTabletV2NameEvent
		l := 0
		nameLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Name = client.String(data[l : l+nameLen])
		l += nameLen

		i.nameHandler(e)
	case 1:
		if i.idHandler == nil {
			return
		}
		var e ZwpTabletV2IdEvent
		l := 0
		e.Vid = client.Uint32(data[l : l+4])
		l += 4
		e.Pid = client.Uint32(data[l : l+4])
		l += 4

		i.idHandler(e)
	case 2:
		if i.pathHandler == nil {
			return
		}
		var e ZwpTabletV2PathEvent
		l := 0
		pathLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Path = client.String(data[l : l+pathLen])
		l += pathLen

		i.pathHandler(e)
	case 3:
		if i.doneHandler == nil {
			return
		}
		var e ZwpTabletV2DoneEvent

		i.doneHandler(e)
	case 4:
		if i.removedHandler == nil {
			return
		}
		var e ZwpTabletV2RemovedEvent

		i.removedHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ZwpTabletPadRingV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletPadRingV2InterfaceName = "zwp_tablet_pad_ring_v2"

// ZwpTabletPadRingV2 : pad ring
//
// A circular interaction area, such as the touch ring on the Wacom Intuos
// Pro series tablets.
//
// Events on a ring are logically grouped by the wl_tablet_pad_ring.frame
// event.
type ZwpTabletPadRingV2 struct {
	client.BaseProxy
	sourceHandler ZwpTabletPadRingV2SourceHandlerFunc
	angleHandler  ZwpTabletPadRingV2AngleHandlerFunc
	stopHandler   ZwpTabletPadRingV2StopHandlerFunc
	frameHandler  ZwpTabletPadRingV2FrameHandlerFunc
}

// NewZwpTabletPadRingV2 : pad ring
//
// A circular interaction area, such as the touch ring on the Wacom Intuos
// Pro series tablets.
//
// Events on a ring are logically grouped by the wl_tablet_pad_ring.frame
// event.
func NewZwpTabletPadRingV2(ctx *client.Context) *ZwpTabletPadRingV2 {
	zwpTabletPadRingV2 := &ZwpTabletPadRingV2{}
	ctx.Register(zwpTabletPadRingV2)
	return zwpTabletPadRingV2
}

// SetFeedback : set compositor feedback
//
// Request that the compositor use the provided feedback string
// associated with this ring. This request should be issued immediately
// after a wp_tablet_pad_group.mode_switch event from the corresponding
// group is received, or whenever the ring is mapped to a different
// action. See wp_tablet_pad_group.mode_switch for more details.
//
// Clients are encouraged to provide context-aware descriptions for
// the actions associated with the ring; compositors may use this
// information to offer visual feedback about the button layout
// (eg. on-screen displays).
//
// The provided string 'description' is a UTF-8 encoded string to be
// associated with this ring, and is considered user-visible; general
// internationalization rules apply.
//
// The serial argument will be that of the last
// wp_tablet_pad_group.mode_switch event received for the group of this
// ring. Requests providing other serials than the most recent one will be
// ignored.
//
//	description: ring description
//	serial: serial of the mode switch event
func (i *ZwpTabletPadRingV2) SetFeedback(description string, serial uint32) error {
	const opcode = 0
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + (4 + descriptionLen) + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description)
	l += (4 + descriptionLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy : destroy the ring object
//
// This destroys the client's resource for this ring object.
func (i *ZwpTabletPadRingV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ZwpTabletPadRingV2Source uint32

// ZwpTabletPadRingV2Source : ring axis source
//
// Describes the source types for ring events. This indicates to the
// client how a ring event was physically generated; a client may
// adjust the user interface accordingly. For example, events
// from a "finger" source may trigger kinetic scrolling.
const (
	// ZwpTabletPadRingV2SourceFinger : finger
	ZwpTabletPadRingV2SourceFinger ZwpTabletPadRingV2Source = 1
)

func (e ZwpTabletPadRingV2Source) Name() string {
	switch e {
	case ZwpTabletPadRingV2SourceFinger:
		return "finger"
	default:
		return ""
	}
}

func (e ZwpTabletPadRingV2Source) Value() string {
	switch e {
	case ZwpTabletPadRingV2SourceFinger:
		return "1"
	default:
		return ""
	}
}

func (e ZwpTabletPadRingV2Source) String() string {
	return e.Name() + "=" + e.Value()
}

// ZwpTabletPadRingV2SourceEvent : ring event source
//
// Source information for ring events.
//
// This event does not occur on its own. It is sent before a
// wp_tablet_pad_ring.frame event and carries the source information
// for all events within that frame.
//
// The source specifies how this event was generated. If the source is
// wp_tablet_pad_ring.source.finger, a wp_tablet_pad_ring.stop event
// will be sent when the user lifts the finger off the device.
//
// This event is optional. If the source is unknown for an interaction,
// no event is sent.
type ZwpTabletPadRingV2SourceEvent struct {
	Source uint32
}
type ZwpTabletPadRingV2SourceHandlerFunc func(ZwpTabletPadRingV2SourceEvent)

// SetSourceHandler : sets handler for ZwpTabletPadRingV2SourceEvent
func (i *ZwpTabletPadRingV2) SetSourceHandler(f ZwpTabletPadRingV2SourceHandlerFunc) {
	i.sourceHandler = f
}

// ZwpTabletPadRingV2AngleEvent : angle changed
//
// Sent whenever the angle on a ring changes.
//
// The angle is provided in degrees clockwise from the logical
// north of the ring in the pad's current rotation.
type ZwpTabletPadRingV2AngleEvent struct {
	Degrees float64
}
type ZwpTabletPadRingV2AngleHandlerFunc func(ZwpTabletPadRingV2AngleEvent)

// SetAngleHandler : sets handler for ZwpTabletPadRingV2AngleEvent
func (i *ZwpTabletPadRingV2) SetAngleHandler(f ZwpTabletPadRingV2AngleHandlerFunc) {
	i.angleHandler = f
}

// ZwpTabletPadRingV2StopEvent : interaction stopped
//
// Stop notification for ring events.
//
// For some wp_tablet_pad_ring.source types, a wp_tablet_pad_ring.stop
// event is sent to notify a client that the interaction with the ring
// has terminated. This enables the client to implement kinetic scrolling.
// See the wp_tablet_pad_ring.source documentation for information on
// when this event may be generated.
//
// Any wp_tablet_pad_ring.angle events with the same source after this
// event should be considered as the start of a new interaction.
type ZwpTabletPadRingV2StopEvent struct{}
type ZwpTabletPadRingV2StopHandlerFunc func(ZwpTabletPadRingV2StopEvent)

// SetStopHandler : sets handler for ZwpTabletPadRingV2StopEvent
func (i *ZwpTabletPadRingV2) SetStopHandler(f ZwpTabletPadRingV2StopHandlerFunc) {
	i.stopHandler = f
}

// ZwpTabletPadRingV2FrameEvent : end of a ring event sequence
//
// Indicates the end of a set of ring events that logically belong
// together. A client is expected to accumulate the data in all events
// within the frame before proceeding.
//
// All wp_tablet_pad_ring events before a wp_tablet_pad_ring.frame event belong
// logically together. For example, on termination of a finger interaction
// on a ring the compositor will send a wp_tablet_pad_ring.source event,
// a wp_tablet_pad_ring.stop event and a wp_tablet_pad_ring.frame event.
//
// A wp_tablet_pad_ring.frame event is sent for every logical event
// group, even if the group only contains a single wp_tablet_pad_ring
// event. Specifically, a client may get a sequence: angle, frame,
// angle, frame, etc.
type ZwpTabletPadRingV2FrameEvent struct {
	Time uint32
}
type ZwpTabletPadRingV2FrameHandlerFunc func(ZwpTabletPadRingV2FrameEvent)

// SetFrameHandler : sets handler for ZwpTabletPadRingV2FrameEvent
func (i *ZwpTabletPadRingV2) SetFrameHandler(f ZwpTabletPadRingV2FrameHandlerFunc) {
	i.frameHandler = f
}

func (i *ZwpTabletPadRingV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.sourceHandler == nil {
			return
		}
		var e ZwpTabletPadRingV2SourceEvent
		l := 0
		e.Source = client.Uint32(data[l : l+4])
		l += 4

		i.sourceHandler(e)
	case 1:
		if i.angleHandler == nil {
			return
		}
		var e ZwpTabletPadRingV2AngleEvent
		l := 0
		e.Degrees = client.Fixed(data[l : l+4])
		l += 4

		i.angleHandler(e)
	case 2:
		if i.stopHandler == nil {
			return
		}
		var e ZwpTabletPadRingV2StopEvent

		i.stopHandler(e)
	case 3:
		if i.frameHandler == nil {
			return
		}
		var e ZwpTabletPadRingV2FrameEvent
		l := 0
		e.Time = client.Uint32(data[l : l+4])
		l += 4

		i.frameHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ZwpTabletPadStripV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletPadStripV2InterfaceName = "zwp_tablet_pad_strip_v2"

// ZwpTabletPadStripV2 : pad strip
//
// A linear interaction area, such as the strips found in Wacom Cintiq
// models.
//
// Events on a strip are logically grouped by the wl_tablet_pad_strip.frame
// event.
type ZwpTabletPadStripV2 struct {
	client.BaseProxy
	sourceHandler   ZwpTabletPadStripV2SourceHandlerFunc
	positionHandler ZwpTabletPadStripV2PositionHandlerFunc
	stopHandler     ZwpTabletPadStripV2StopHandlerFunc
	frameHandler    ZwpTabletPadStripV2FrameHandlerFunc
}

// NewZwpTabletPadStripV2 : pad strip
//
// A linear interaction area, such as the strips found in Wacom Cintiq
// models.
//
// Events on a strip are logically grouped by the wl_tablet_pad_strip.frame
// event.
func NewZwpTabletPadStripV2(ctx *client.Context) *ZwpTabletPadStripV2 {
	zwpTabletPadStripV2 := &ZwpTabletPadStripV2{}
	ctx.Register(zwpTabletPadStripV2)
	return zwpTabletPadStripV2
}

// SetFeedback : set compositor feedback
//
// Requests the compositor to use the provided feedback string
// associated with this strip. This request should be issued immediately
// after a wp_tablet_pad_group.mode_switch event from the corresponding
// group is received, or whenever the strip is mapped to a different
// action. See wp_tablet_pad_group.mode_switch for more details.
//
// Clients are encouraged to provide context-aware descriptions for
// the actions associated with the strip, and compositors may use this
// information to offer visual feedback about the button layout
// (eg. on-screen displays).
//
// The provided string 'description' is a UTF-8 encoded string to be
// associated with this ring, and is considered user-visible; general
// internationalization rules apply.
//
// The serial argument will be that of the last
// wp_tablet_pad_group.mode_switch event received for the group of this
// strip. Requests providing other serials than the most recent one will be
// ignored.
//
//	description: strip description
//	serial: serial of the mode switch event
func (i *ZwpTabletPadStripV2) SetFeedback(description string, serial uint32) error {
	const opcode = 0
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + (4 + descriptionLen) + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description)
	l += (4 + descriptionLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy : destroy the strip object
//
// This destroys the client's resource for this strip object.
func (i *ZwpTabletPadStripV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ZwpTabletPadStripV2Source uint32

// ZwpTabletPadStripV2Source : strip axis source
//
// Describes the source types for strip events. This indicates to the
// client how a strip event was physically generated; a client may
// adjust the user interface accordingly. For example, events
// from a "finger" source may trigger kinetic scrolling.
const (
	// ZwpTabletPadStripV2SourceFinger : finger
	ZwpTabletPadStripV2SourceFinger ZwpTabletPadStripV2Source = 1
)

func (e ZwpTabletPadStripV2Source) Name() string {
	switch e {
	case ZwpTabletPadStripV2SourceFinger:
		return "finger"
	default:
		return ""
	}
}

func (e ZwpTabletPadStripV2Source) Value() string {
	switch e {
	case ZwpTabletPadStripV2SourceFinger:
		return "1"
	default:
		return ""
	}
}

func (e ZwpTabletPadStripV2Source) String() string {
	return e.Name() + "=" + e.Value()
}

// ZwpTabletPadStripV2SourceEvent : strip event source
//
// Source information for strip events.
//
// This event does not occur on its own. It is sent before a
// wp_tablet_pad_strip.frame event and carries the source information
// for all events within that frame.
//
// The source specifies how this event was generated. If the source is
// wp_tablet_pad_strip.source.finger, a wp_tablet_pad_strip.stop event
// will be sent when the user lifts their finger off the device.
//
// This event is optional. If the source is unknown for an interaction,
// no event is sent.
type ZwpTabletPadStripV2SourceEvent struct {
	Source uint32
}
type ZwpTabletPadStripV2SourceHandlerFunc func(ZwpTabletPadStripV2SourceEvent)

// SetSourceHandler : sets handler for ZwpTabletPadStripV2SourceEvent
func (i *ZwpTabletPadStripV2) SetSourceHandler(f ZwpTabletPadStripV2SourceHandlerFunc) {
	i.sourceHandler = f
}

// ZwpTabletPadStripV2PositionEvent : position changed
//
// Sent whenever the position on a strip changes.
//
// The position is normalized to a range of [0, 65535], the 0-value
// represents the top-most and/or left-most position of the strip in
// the pad's current rotation.
type ZwpTabletPadStripV2PositionEvent struct {
	Position uint32
}
type ZwpTabletPadStripV2PositionHandlerFunc func(ZwpTabletPadStripV2PositionEvent)

// SetPositionHandler : sets handler for ZwpTabletPadStripV2PositionEvent
func (i *ZwpTabletPadStripV2) SetPositionHandler(f ZwpTabletPadStripV2PositionHandlerFunc) {
	i.positionHandler = f
}

// ZwpTabletPadStripV2StopEvent : interaction stopped
//
// Stop notification for strip events.
//
// For some wp_tablet_pad_strip.source types, a wp_tablet_pad_strip.stop
// event is sent to notify a client that the interaction with the strip
// has terminated. This enables the client to implement kinetic
// scrolling. See the wp_tablet_pad_strip.source documentation for
// information on when this event may be generated.
//
// Any wp_tablet_pad_strip.position events with the same source after this
// event should be considered as the start of a new interaction.
type ZwpTabletPadStripV2StopEvent struct{}
type ZwpTabletPadStripV2StopHandlerFunc func(ZwpTabletPadStripV2StopEvent)

// SetStopHandler : sets handler for ZwpTabletPadStripV2StopEvent
func (i *ZwpTabletPadStripV2) SetStopHandler(f ZwpTabletPadStripV2StopHandlerFunc) {
	i.stopHandler = f
}

// ZwpTabletPadStripV2FrameEvent : end of a strip event sequence
//
// Indicates the end of a set of events that represent one logical
// hardware strip event. A client is expected to accumulate the data
// in all events within the frame before proceeding.
//
// All wp_tablet_pad_strip events before a wp_tablet_pad_strip.frame event belong
// logically together. For example, on termination of a finger interaction
// on a strip the compositor will send a wp_tablet_pad_strip.source event,
// a wp_tablet_pad_strip.stop event and a wp_tablet_pad_strip.frame
// event.
//
// A wp_tablet_pad_strip.frame event is sent for every logical event
// group, even if the group only contains a single wp_tablet_pad_strip
// event. Specifically, a client may get a sequence: position, frame,
// position, frame, etc.
type ZwpTabletPadStripV2FrameEvent struct {
	Time uint32
}
type ZwpTabletPadStripV2FrameHandlerFunc func(ZwpTabletPadStripV2FrameEvent)

// SetFrameHandler : sets handler for ZwpTabletPadStripV2FrameEvent
func (i *ZwpTabletPadStripV2) SetFrameHandler(f ZwpTabletPadStripV2FrameHandlerFunc) {
	i.frameHandler = f
}

func (i *ZwpTabletPadStripV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.sourceHandler == nil {
			return
		}
		var e ZwpTabletPadStripV2SourceEvent
		l := 0
		e.Source = client.Uint32(data[l : l+4])
		l += 4

		i.sourceHandler(e)
	case 1:
		if i.positionHandler == nil {
			return
		}
		var e ZwpTabletPadStripV2PositionEvent
		l := 0
		e.Position = client.Uint32(data[l : l+4])
		l += 4

		i.positionHandler(e)
	case 2:
		if i.stopHandler == nil {
			return
		}
		var e ZwpTabletPadStripV2StopEvent

		i.stopHandler(e)
	case 3:
		if i.frameHandler == nil {
			return
		}
		var e ZwpTabletPadStripV2FrameEvent
		l := 0
		e.Time = client.Uint32(data[l : l+4])
		l += 4

		i.frameHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ZwpTabletPadGroupV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletPadGroupV2InterfaceName = "zwp_tablet_pad_group_v2"

// ZwpTabletPadGroupV2 : a set of buttons, rings and strips
//
// A pad group describes a distinct (sub)set of buttons, rings and strips
// present in the tablet. The criteria of this grouping is usually positional,
// eg. if a tablet has buttons on the left and right side, 2 groups will be
// presented. The physical arrangement of groups is undisclosed and may
// change on the fly.
//
// Pad groups will announce their features during pad initialization. Between
// the corresponding wp_tablet_pad.group event and wp_tablet_pad_group.done, the
// pad group will announce the buttons, rings and strips contained in it,
// plus the number of supported modes.
//
// Modes are a mechanism to allow multiple groups of actions for every element
// in the pad group. The number of groups and available modes in each is
// persistent across device plugs. The current mode is user-switchable, it
// will be announced through the wp_tablet_pad_group.mode_switch event both
// whenever it is switched, and after wp_tablet_pad.enter.
//
// The current mode logically applies to all elements in the pad group,
// although it is at clients' discretion whether to actually perform different
// actions, and/or issue the respective .set_feedback requests to notify the
// compositor. See the wp_tablet_pad_group.mode_switch event for more details.
type ZwpTabletPadGroupV2 struct {
	client.BaseProxy
	buttonsHandler    ZwpTabletPadGroupV2ButtonsHandlerFunc
	ringHandler       ZwpTabletPadGroupV2RingHandlerFunc
	stripHandler      ZwpTabletPadGroupV2StripHandlerFunc
	modesHandler      ZwpTabletPadGroupV2ModesHandlerFunc
	doneHandler       ZwpTabletPadGroupV2DoneHandlerFunc
	modeSwitchHandler ZwpTabletPadGroupV2ModeSwitchHandlerFunc
}

// NewZwpTabletPadGroupV2 : a set of buttons, rings and strips
//
// A pad group describes a distinct (sub)set of buttons, rings and strips
// present in the tablet. The criteria of this grouping is usually positional,
// eg. if a tablet has buttons on the left and right side, 2 groups will be
// presented. The physical arrangement of groups is undisclosed and may
// change on the fly.
//
// Pad groups will announce their features during pad initialization. Between
// the corresponding wp_tablet_pad.group event and wp_tablet_pad_group.done, the
// pad group will announce the buttons, rings and strips contained in it,
// plus the number of supported modes.
//
// Modes are a mechanism to allow multiple groups of actions for every element
// in the pad group. The number of groups and available modes in each is
// persistent across device plugs. The current mode is user-switchable, it
// will be announced through the wp_tablet_pad_group.mode_switch event both
// whenever it is switched, and after wp_tablet_pad.enter.
//
// The current mode logically applies to all elements in the pad group,
// although it is at clients' discretion whether to actually perform different
// actions, and/or issue the respective .set_feedback requests to notify the
// compositor. See the wp_tablet_pad_group.mode_switch event for more details.
func NewZwpTabletPadGroupV2(ctx *client.Context) *ZwpTabletPadGroupV2 {
	zwpTabletPadGroupV2 := &ZwpTabletPadGroupV2{}
	ctx.Register(zwpTabletPadGroupV2)
	return zwpTabletPadGroupV2
}

// Destroy : destroy the pad object
//
// Destroy the wp_tablet_pad_group object. Objects created from this object
// are unaffected and should be destroyed separately.
func (i *ZwpTabletPadGroupV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletPadGroupV2ButtonsEvent : buttons announced
//
// Sent on wp_tablet_pad_group initialization to announce the available
// buttons in the group. Button indices start at 0, a button may only be
// in one group at a time.
//
// This event is first sent in the initial burst of events before the
// wp_tablet_pad_group.done event.
//
// Some buttons are reserved by the compositor. These buttons may not be
// assigned to any wp_tablet_pad_group. Compositors may broadcast this
// event in the case of changes to the mapping of these reserved buttons.
// If the compositor happens to reserve all buttons in a group, this event
// will be sent with an empty array.
type ZwpTabletPadGroupV2ButtonsEvent struct {
	Buttons []byte
}
type ZwpTabletPadGroupV2ButtonsHandlerFunc func(ZwpTabletPadGroupV2ButtonsEvent)

// SetButtonsHandler : sets handler for ZwpTabletPadGroupV2ButtonsEvent
func (i *ZwpTabletPadGroupV2) SetButtonsHandler(f ZwpTabletPadGroupV2ButtonsHandlerFunc) {
	i.buttonsHandler = f
}

// ZwpTabletPadGroupV2RingEvent : ring announced
//
// Sent on wp_tablet_pad_group initialization to announce available rings.
// One event is sent for each ring available on this pad group.
//
// This event is sent in the initial burst of events before the
// wp_tablet_pad_group.done event.
type ZwpTabletPadGroupV2RingEvent struct {
	Ring *ZwpTabletPadRingV2
}
type ZwpTabletPadGroupV2RingHandlerFunc func(ZwpTabletPadGroupV2RingEvent)

// SetRingHandler : sets handler for ZwpTabletPadGroupV2RingEvent
func (i *ZwpTabletPadGroupV2) SetRingHandler(f ZwpTabletPadGroupV2RingHandlerFunc) {
	i.ringHandler = f
}

// ZwpTabletPadGroupV2StripEvent : strip announced
//
// Sent on wp_tablet_pad initialization to announce available strips.
// One event is sent for each strip available on this pad group.
//
// This event is sent in the initial burst of events before the
// wp_tablet_pad_group.done event.
type ZwpTabletPadGroupV2StripEvent struct {
	Strip *ZwpTabletPadStripV2
}
type ZwpTabletPadGroupV2StripHandlerFunc func(ZwpTabletPadGroupV2StripEvent)

// SetStripHandler : sets handler for ZwpTabletPadGroupV2StripEvent
func (i *ZwpTabletPadGroupV2) SetStripHandler(f ZwpTabletPadGroupV2StripHandlerFunc) {
	i.stripHandler = f
}

// ZwpTabletPadGroupV2ModesEvent : mode-switch ability announced
//
// Sent on wp_tablet_pad_group initialization to announce that the pad
// group may switch between modes. A client may use a mode to store a
// specific configuration for buttons, rings and strips and use the
// wl_tablet_pad_group.mode_switch event to toggle between these
// configurations. Mode indices start at 0.
//
// Switching modes is compositor-dependent. See the
// wp_tablet_pad_group.mode_switch event for more details.
//
// This event is sent in the initial burst of events before the
// wp_tablet_pad_group.done event. This event is only sent when more than
// more than one mode is available.
type ZwpTabletPadGroupV2ModesEvent struct {
	Modes uint32
}
type ZwpTabletPadGroupV2ModesHandlerFunc func(ZwpTabletPadGroupV2ModesEvent)

// SetModesHandler : sets handler for ZwpTabletPadGroupV2ModesEvent
func (i *ZwpTabletPadGroupV2) SetModesHandler(f ZwpTabletPadGroupV2ModesHandlerFunc) {
	i.modesHandler = f
}

// ZwpTabletPadGroupV2DoneEvent : tablet group description events sequence complete
//
// This event is sent immediately to signal the end of the initial
// burst of descriptive events. A client may consider the static
// description of the tablet to be complete and finalize initialization
// of the tablet group.
type ZwpTabletPadGroupV2DoneEvent struct{}
type ZwpTabletPadGroupV2DoneHandlerFunc func(ZwpTabletPadGroupV2DoneEvent)

// SetDoneHandler : sets handler for ZwpTabletPadGroupV2DoneEvent
func (i *ZwpTabletPadGroupV2) SetDoneHandler(f ZwpTabletPadGroupV2DoneHandlerFunc) {
	i.doneHandler = f
}

// ZwpTabletPadGroupV2ModeSwitchEvent : mode switch event
//
// Notification that the mode was switched.
//
// A mode applies to all buttons, rings and strips in a group
// simultaneously, but a client is not required to assign different actions
// for each mode. For example, a client may have mode-specific button
// mappings but map the ring to vertical scrolling in all modes. Mode
// indices start at 0.
//
// Switching modes is compositor-dependent. The compositor may provide
// visual cues to the client about the mode, e.g. by toggling LEDs on
// the tablet device. Mode-switching may be software-controlled or
// controlled by one or more physical buttons. For example, on a Wacom
// Intuos Pro, the button inside the ring may be assigned to switch
// between modes.
//
// The compositor will also send this event after wp_tablet_pad.enter on
// each group in order to notify of the current mode. Groups that only
// feature one mode will use mode=0 when emitting this event.
//
// If a button action in the new mode differs from the action in the
// previous mode, the client should immediately issue a
// wp_tablet_pad.set_feedback request for each changed button.
//
// If a ring or strip action in the new mode differs from the action
// in the previous mode, the client should immediately issue a
// wp_tablet_ring.set_feedback or wp_tablet_strip.set_feedback request
// for each changed ring or strip.
type ZwpTabletPadGroupV2ModeSwitchEvent struct {
	Time   uint32
	Serial uint32
	Mode   uint32
}
type ZwpTabletPadGroupV2ModeSwitchHandlerFunc func(ZwpTabletPadGroupV2ModeSwitchEvent)

// SetModeSwitchHandler : sets handler for ZwpTabletPadGroupV2ModeSwitchEvent
func (i *ZwpTabletPadGroupV2) SetModeSwitchHandler(f ZwpTabletPadGroupV2ModeSwitchHandlerFunc) {
	i.modeSwitchHandler = f
}

func (i *ZwpTabletPadGroupV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.buttonsHandler == nil {
			return
		}
		var e ZwpTabletPadGroupV2ButtonsEvent
		l := 0
		buttonsLen := int(client.Uint32(data[l : l+4]))
		l += 4
		e.Buttons = make([]byte, buttonsLen)
		copy(e.Buttons, data[l:l+buttonsLen])
		l += buttonsLen

		i.buttonsHandler(e)
	case 1:
		if i.ringHandler == nil {
			return
		}
		var e ZwpTabletPadGroupV2RingEvent
		l := 0
		ringID := client.Uint32(data[l : l+4])
		if ring, ok := i.Context().GetProxy(ringID).(*ZwpTabletPadRingV2); ok && !ring.IsZombie() {
			e.Ring = ring
		} else if ringID != 0 {
			ring := &ZwpTabletPadRingV2{}
			i.Context().RegisterWithID(ring, ringID)
			e.Ring = ring
		}
		l += 4

		i.ringHandler(e)
	case 2:
		if i.stripHandler == nil {
			return
		}
		var e ZwpTabletPadGroupV2StripEvent
		l := 0
		stripID := client.Uint32(data[l : l+4])
		if strip, ok := i.Context().GetProxy(stripID).(*ZwpTabletPadStripV2); ok && !strip.IsZombie() {
			e.Strip = strip
		} else if stripID != 0 {
			strip := &ZwpTabletPadStripV2{}
			i.Context().RegisterWithID(strip, stripID)
			e.Strip = strip
		}
		l += 4

		i.stripHandler(e)
	case 3:
		if i.modesHandler == nil {
			return
		}
		var e ZwpTabletPadGroupV2ModesEvent
		l := 0
		e.Modes = client.Uint32(data[l : l+4])
		l += 4

		i.modesHandler(e)
	case 4:
		if i.doneHandler == nil {
			return
		}
		var e ZwpTabletPadGroupV2DoneEvent

		i.doneHandler(e)
	case 5:
		if i.modeSwitchHandler == nil {
			return
		}
		var e ZwpTabletPadGroupV2ModeSwitchEvent
		l := 0
		e.Time = client.Uint32(data[l : l+4])
		l += 4
		e.Serial = client.Uint32(data[l : l+4])
		l += 4
		e.Mode = client.Uint32(data[l : l+4])
		l += 4

		i.modeSwitchHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ZwpTabletPadV2InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTabletPadV2InterfaceName = "zwp_tablet_pad_v2"

// ZwpTabletPadV2 : a set of buttons, rings and strips
//
// A pad device is a set of buttons, rings and strips
// usually physically present on the tablet device itself. Some
// exceptions exist where the pad device is physically detached, e.g. the
// Wacom ExpressKey Remote.
//
// Pad devices have no axes that control the cursor and are generally
// auxiliary devices to the tool devices used on the tablet surface.
//
// A pad device has a number of static characteristics, e.g. the number
// of rings. These capabilities are sent in an event sequence after the
// wp_tablet_seat.pad_added event before any actual events from this pad.
// This initial event sequence is terminated by a wp_tablet_pad.done
// event.
//
// All pad features (buttons, rings and strips) are logically divided into
// groups and all pads have at least one group. The available groups are
// notified through the wp_tablet_pad.group event; the compositor will
// emit one event per group before emitting wp_tablet_pad.done.
//
// Groups may have multiple modes. Modes allow clients to map multiple
// actions to a single pad feature. Only one mode can be active per group,
// although different groups may have different active modes.
type ZwpTabletPadV2 struct {
	client.BaseProxy
	groupHandler   ZwpTabletPadV2GroupHandlerFunc
	pathHandler    ZwpTabletPadV2PathHandlerFunc
	buttonsHandler ZwpTabletPadV2ButtonsHandlerFunc
	doneHandler    ZwpTabletPadV2DoneHandlerFunc
	buttonHandler  ZwpTabletPadV2ButtonHandlerFunc
	enterHandler   ZwpTabletPadV2EnterHandlerFunc
	leaveHandler   ZwpTabletPadV2LeaveHandlerFunc
	removedHandler ZwpTabletPadV2RemovedHandlerFunc
}

// NewZwpTabletPadV2 : a set of buttons, rings and strips
//
// A pad device is a set of buttons, rings and strips
// usually physically present on the tablet device itself. Some
// exceptions exist where the pad device is physically detached, e.g. the
// Wacom ExpressKey Remote.
//
// Pad devices have no axes that control the cursor and are generally
// auxiliary devices to the tool devices used on the tablet surface.
//
// A pad device has a number of static characteristics, e.g. the number
// of rings. These capabilities are sent in an event sequence after the
// wp_tablet_seat.pad_added event before any actual events from this pad.
// This initial event sequence is terminated by a wp_tablet_pad.done
// event.
//
// All pad features (buttons, rings and strips) are logically divided into
// groups and all pads have at least one group. The available groups are
// notified through the wp_tablet_pad.group event; the compositor will
// emit one event per group before emitting wp_tablet_pad.done.
//
// Groups may have multiple modes. Modes allow clients to map multiple
// actions to a single pad feature. Only one mode can be active per group,
// although different groups may have different active modes.
func NewZwpTabletPadV2(ctx *client.Context) *ZwpTabletPadV2 {
	zwpTabletPadV2 := &ZwpTabletPadV2{}
	ctx.Register(zwpTabletPadV2)
	return zwpTabletPadV2
}

// SetFeedback : set compositor feedback
//
// Requests the compositor to use the provided feedback string
// associated with this button. This request should be issued immediately
// after a wp_tablet_pad_group.mode_switch event from the corresponding
// group is received, or whenever a button is mapped to a different
// action. See wp_tablet_pad_group.mode_switch for more details.
//
// Clients are encouraged to provide context-aware descriptions for
// the actions associated with each button, and compositors may use
// this information to offer visual feedback on the button layout
// (e.g. on-screen displays).
//
// Button indices start at 0. Setting the feedback string on a button
// that is reserved by the compositor (i.e. not belonging to any
// wp_tablet_pad_group) does not generate an error but the compositor
// is free to ignore the request.
//
// The provided string 'description' is a UTF-8 encoded string to be
// associated with this ring, and is considered user-visible; general
// internationalization rules apply.
//
// The serial argument will be that of the last
// wp_tablet_pad_group.mode_switch event received for the group of this
// button. Requests providing other serials than the most recent one will
// be ignored.
//
//	button: button index
//	description: button description
//	serial: serial of the mode switch event
func (i *ZwpTabletPadV2) SetFeedback(button uint32, description string, serial uint32) error {
	const opcode = 0
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + 4 + (4 + descriptionLen) + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(button))
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description)
	l += (4 + descriptionLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy : destroy the pad object
//
// Destroy the wp_tablet_pad object. Objects created from this object
// are unaffected and should be destroyed separately.
func (i *ZwpTabletPadV2) Destroy() error {
	defer i.MarkZombie()
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ZwpTabletPadV2ButtonState uint32

// ZwpTabletPadV2ButtonState : physical button state
//
// Describes the physical state of a button that caused the button
// event.
const (
	// ZwpTabletPadV2ButtonStateReleased : the button is not pressed
	ZwpTabletPadV2ButtonStateReleased ZwpTabletPadV2ButtonState = 0
	// ZwpTabletPadV2ButtonStatePressed : the button is pressed
	ZwpTabletPadV2ButtonStatePressed ZwpTabletPadV2ButtonState = 1
)

func (e ZwpTabletPadV2ButtonState) Name() string {
	switch e {
	case ZwpTabletPadV2ButtonStateReleased:
		return "released"
	case ZwpTabletPadV2ButtonStatePressed:
		return "pressed"
	default:
		return ""
	}
}

func (e ZwpTabletPadV2ButtonState) Value() string {
	switch e {
	case ZwpTabletPadV2ButtonStateReleased:
		return "0"
	case ZwpTabletPadV2ButtonStatePressed:
		return "1"
	default:
		return ""
	}
}

func (e ZwpTabletPadV2ButtonState) String() string {
	return e.Name() + "=" + e.Value()
}

// ZwpTabletPadV2GroupEvent : group announced
//
// Sent on wp_tablet_pad initialization to announce available groups.
// One event is sent for each pad group available.
//
// This event is sent in the initial burst of events before the
// wp_tablet_pad.done event. At least one group will be announced.
type ZwpTabletPadV2GroupEvent struct {
	PadGroup *ZwpTabletPadGroupV2
}
type ZwpTabletPadV2GroupHandlerFunc func(ZwpTabletPadV2GroupEvent)

// SetGroupHandler : sets handler for ZwpTabletPadV2GroupEvent
func (i *ZwpTabletPadV2) SetGroupHandler(f ZwpTabletPadV2GroupHandlerFunc) {
	i.groupHandler = f
}

// ZwpTabletPadV2PathEvent : path to the device
//
// A system-specific device path that indicates which device is behind
// this wp_tablet_pad. This information may be used to gather additional
// information about the device, e.g. through libwacom.
//
// The format of the path is unspecified, it may be a device node, a
// sysfs path, or some other identifier. It is up to the client to
// identify the string provided.
//
// This event is sent in the initial burst of events before the
// wp_tablet_pad.done event.
type ZwpTabletPadV2PathEvent struct {
	Path string
}
type ZwpTabletPadV2PathHandlerFunc func(ZwpTabletPadV2PathEvent)

// SetPathHandler : sets handler for ZwpTabletPadV2PathEvent
func (i *ZwpTabletPadV2) SetPathHandler(f ZwpTabletPadV2PathHandlerFunc) {
	i.pathHandler = f
}

// ZwpTabletPadV2ButtonsEvent : buttons announced
//
// Sent on wp_tablet_pad initialization to announce the available
// buttons.
//
// This event is sent in the initial burst of events before the
// wp_tablet_pad.done event. This event is only sent when at least one
// button is available.
type ZwpTabletPadV2ButtonsEvent struct {
	Buttons uint32
}
type ZwpTabletPadV2ButtonsHandlerFunc func(ZwpTabletPadV2ButtonsEvent)

// SetButtonsHandler : sets handler for ZwpTabletPadV2ButtonsEvent
func (i *ZwpTabletPadV2) SetButtonsHandler(f ZwpTabletPadV2ButtonsHandlerFunc) {
	i.buttonsHandler = f
}

// ZwpTabletPadV2DoneEvent : pad description event sequence complete
//
// This event signals the end of the initial burst of descriptive
// events. A client may consider the static description of the pad to
// be complete and finalize initialization of the pad.
type ZwpTabletPadV2DoneEvent struct{}
type ZwpTabletPadV2DoneHandlerFunc func(ZwpTabletPadV2DoneEvent)

// SetDoneHandler : sets handler for ZwpTabletPadV2DoneEvent
func (i *ZwpTabletPadV2) SetDoneHandler(f ZwpTabletPadV2DoneHandlerFunc) {
	i.doneHandler = f
}

// ZwpTabletPadV2ButtonEvent : physical button state
//
// Sent whenever the physical state of a button changes.
type ZwpTabletPadV2ButtonEvent struct {
	Time   uint32
	Button uint32
	State  uint32
}
type ZwpTabletPadV2ButtonHandlerFunc func(ZwpTabletPadV2ButtonEvent)

// SetButtonHandler : sets handler for ZwpTabletPadV2ButtonEvent
func (i *ZwpTabletPadV2) SetButtonHandler(f ZwpTabletPadV2ButtonHandlerFunc) {
	i.buttonHandler = f
}

// ZwpTabletPadV2EnterEvent : enter event
//
// Notification that this pad is focused on the specified surface.
type ZwpTabletPadV2EnterEvent struct {
	Serial  uint32
	Tablet  *ZwpTabletV2
	Surface *client.Surface
}
type ZwpTabletPadV2EnterHandlerFunc func(ZwpTabletPadV2EnterEvent)

// SetEnterHandler : sets handler for ZwpTabletPadV2EnterEvent
func (i *ZwpTabletPadV2) SetEnterHandler(f ZwpTabletPadV2EnterHandlerFunc) {
	i.enterHandler = f
}

// ZwpTabletPadV2LeaveEvent : leave event
//
// Notification that this pad is no longer focused on the specified
// surface.
type ZwpTabletPadV2LeaveEvent struct {
	Serial  uint32
	Surface *client.Surface
}
type ZwpTabletPadV2LeaveHandlerFunc func(ZwpTabletPadV2LeaveEvent)

// SetLeaveHandler : sets handler for ZwpTabletPadV2LeaveEvent
func (i *ZwpTabletPadV2) SetLeaveHandler(f ZwpTabletPadV2LeaveHandlerFunc) {
	i.leaveHandler = f
}

// ZwpTabletPadV2RemovedEvent : pad removed event
//
// Sent when the pad has been removed from the system. When a tablet
// is removed its pad(s) will be removed too.
//
// When this event is received, the client must destroy all rings, strips
// and groups that were offered by this pad, and issue wp_tablet_pad.destroy
// the pad itself.
type ZwpTabletPadV2RemovedEvent struct{}
type ZwpTabletPadV2RemovedHandlerFunc func(ZwpTabletPadV2RemovedEvent)

// SetRemovedHandler : sets handler for ZwpTabletPadV2RemovedEvent
func (i *ZwpTabletPadV2) SetRemovedHandler(f ZwpTabletPadV2RemovedHandlerFunc) {
	i.removedHandler = f
}

func (i *ZwpTabletPadV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.groupHandler == nil {
			return
		}
		var e ZwpTabletPadV2GroupEvent
		l := 0
		padGroupID := client.Uint32(data[l : l+4])
		if padGroup, ok := i.Context().GetProxy(padGroupID).(*ZwpTabletPadGroupV2); ok && !padGroup.IsZombie() {
			e.PadGroup = padGroup
		} else if padGroupID != 0 {
			padGroup := &ZwpTabletPadGroupV2{}
			i.Context().RegisterWithID(padGroup, padGroupID)
			e.PadGroup = padGroup
		}
		l += 4

		i.groupHandler(e)
	case 1:
		if i.pathHandler == nil {
			return
		}
		var e ZwpTabletPadV2PathEvent
		l := 0
		pathLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Path = client.String(data[l : l+pathLen])
		l += pathLen

		i.pathHandler(e)
	case 2:
		if i.buttonsHandler == nil {
			return
		}
		var e ZwpTabletPadV2ButtonsEvent
		l := 0
		e.Buttons = client.Uint32(data[l : l+4])
		l += 4

		i.buttonsHandler(e)
	case 3:
		if i.doneHandler == nil {
			return
		}
		var e ZwpTabletPadV2DoneEvent

		i.doneHandler(e)
	case 4:
		if i.buttonHandler == nil {
			return
		}
		var e ZwpTabletPadV2ButtonEvent
		l := 0
		e.Time = client.Uint32(data[l : l+4])
		l += 4
		e.Button = client.Uint32(data[l : l+4])
		l += 4
		e.State = client.Uint32(data[l : l+4])
		l += 4

		i.buttonHandler(e)
	case 5:
		if i.enterHandler == nil {
			return
		}
		var e ZwpTabletPadV2EnterEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4
		tabletID := client.Uint32(data[l : l+4])
		if tablet, ok := i.Context().GetProxy(tabletID).(*ZwpTabletV2); ok && !tablet.IsZombie() {
			e.Tablet = tablet
		} else {
			e.Tablet = nil
		}
		l += 4
		surfaceID := client.Uint32(data[l : l+4])
		if surface, ok := i.Context().GetProxy(surfaceID).(*client.Surface); ok && !surface.IsZombie() {
			e.Surface = surface
		} else {
			e.Surface = nil
		}
		l += 4

		i.enterHandler(e)
	case 6:
		if i.leaveHandler == nil {
			return
		}
		var e ZwpTabletPadV2LeaveEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4
		surfaceID := client.Uint32(data[l : l+4])
		if surface, ok := i.Context().GetProxy(surfaceID).(*client.Surface); ok && !surface.IsZombie() {
			e.Surface = surface
		} else {
			e.Surface = nil
		}
		l += 4

		i.leaveHandler(e)
	case 7:
		if i.removedHandler == nil {
			return
		}
		var e ZwpTabletPadV2RemovedEvent

		i.removedHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}
