// Generated by go-wayland-scanner
// https://github.com/Nomadcxx/sysc-wayland/cmd/sysc-wayland-scanner
// XML file : protocols/text-input-unstable-v3.xml
//
// text_input_unstable_v3 Protocol Copyright:
//
// Copyright © 2012, 2013 Intel Corporation
// Copyright © 2015, 2016 Jan Arne Petersen
// Copyright © 2017, 2018 Red Hat, Inc.
// Copyright © 2018       Purism SPC
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package textinput

import "github.com/Nomadcxx/sysc-wayland/client"

// ZwpTextInputV3InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTextInputV3InterfaceName = "zwp_text_input_v3"

// ZwpTextInputV3 : text input
//
// The zwp_text_input_v3 interface represents text input and input methods
// associated with a seat. It provides enter/leave events to follow the
// text input focus for a seat.
//
// Requests are used to enable/disable the text-input object and set
// state information like surrounding and selected text or the content type.
// The information about the entered text is sent to the text-input object
// via the preedit_string and commit_string events.
//
// Text is valid UTF-8 encoded, indices and lengths are in bytes. Indices
// must not point to middle bytes inside a code point: they must either
// point to the first byte of a code point or to the end of the buffer.
// Lengths must be measured between two valid indices.
//
// Focus moving throughout surfaces will result in the emission of
// zwp_text_input_v3.enter and zwp_text_input_v3.leave events. The focused
// surface must commit zwp_text_input_v3.enable and
// zwp_text_input_v3.disable requests as the keyboard focus moves across
// editable and non-editable elements of the UI. Those two requests are not
// expected to be paired with each other, the compositor must be able to
// handle consecutive series of the same request.
//
// State is sent by the state requests (set_surrounding_text,
// set_content_type and set_cursor_rectangle) and a commit request. After an
// enter event or disable request all state information is invalidated and
// needs to be resent by the client.
type ZwpTextInputV3 struct {
	client.BaseProxy
	enterHandler                 ZwpTextInputV3EnterHandlerFunc
	leaveHandler                 ZwpTextInputV3LeaveHandlerFunc
	preeditStringHandler         ZwpTextInputV3PreeditStringHandlerFunc
	commitStringHandler          ZwpTextInputV3CommitStringHandlerFunc
	deleteSurroundingTextHandler ZwpTextInputV3DeleteSurroundingTextHandlerFunc
	doneHandler                  ZwpTextInputV3DoneHandlerFunc
}

// NewZwpTextInputV3 : text input
//
// The zwp_text_input_v3 interface represents text input and input methods
// associated with a seat. It provides enter/leave events to follow the
// text input focus for a seat.
//
// Requests are used to enable/disable the text-input object and set
// state information like surrounding and selected text or the content type.
// The information about the entered text is sent to the text-input object
// via the preedit_string and commit_string events.
//
// Text is valid UTF-8 encoded, indices and lengths are in bytes. Indices
// must not point to middle bytes inside a code point: they must either
// point to the first byte of a code point or to the end of the buffer.
// Lengths must be measured between two valid indices.
//
// Focus moving throughout surfaces will result in the emission of
// zwp_text_input_v3.enter and zwp_text_input_v3.leave events. The focused
// surface must commit zwp_text_input_v3.enable and
// zwp_text_input_v3.disable requests as the keyboard focus moves across
// editable and non-editable elements of the UI. Those two requests are not
// expected to be paired with each other, the compositor must be able to
// handle consecutive series of the same request.
//
// State is sent by the state requests (set_surrounding_text,
// set_content_type and set_cursor_rectangle) and a commit request. After an
// enter event or disable request all state information is invalidated and
// needs to be resent by the client.
func NewZwpTextInputV3(ctx *client.Context) *ZwpTextInputV3 {
	zwpTextInputV3 := &ZwpTextInputV3{}
	ctx.Register(zwpTextInputV3)
	return zwpTextInputV3
}

// Destroy : Destroy the wp_text_input
//
// Destroy the wp_text_input object. Also disables all surfaces enabled
// through this wp_text_input object.
func (i *ZwpTextInputV3) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Enable : Request text input to be enabled
//
// Requests text input on the surface previously obtained from the enter
// event.
//
// This request must be issued every time the focused text input changes
// to a new one, including within the current surface. Use
// zwp_text_input_v3.disable when there is no longer any input focus on
// the current surface.
//
// Clients must not enable more than one text input on the single seat
// and should disable the current text input before enabling the new one.
// Requests to enable a text input when another text input is enabled
// on the same seat must be ignored by compositor.
//
// This request resets all state associated with previous enable, disable,
// set_surrounding_text, set_text_change_cause, set_content_type, and
// set_cursor_rectangle requests, as well as the state associated with
// preedit_string, commit_string, and delete_surrounding_text events.
//
// The set_surrounding_text, set_content_type and set_cursor_rectangle
// requests must follow if the text input supports the necessary
// functionality.
//
// State set with this request is double-buffered. It will get applied on
// the next zwp_text_input_v3.commit request, and stay valid until the
// next committed enable or disable request.
//
// The changes must be applied by the compositor after issuing a
// zwp_text_input_v3.commit request.
func (i *ZwpTextInputV3) Enable() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Disable : Disable text input on a surface
//
// Explicitly disable text input on the current surface (typically when
// there is no focus on any text entry inside the surface).
//
// State set with this request is double-buffered. It will get applied on
// the next zwp_text_input_v3.commit request.
func (i *ZwpTextInputV3) Disable() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSurroundingText : sets the surrounding text
//
// Sets the surrounding plain text around the input, excluding the preedit
// text.
//
// The client should notify the compositor of any changes in any of the
// values carried with this request, including changes caused by handling
// incoming text-input events as well as changes caused by other
// mechanisms like keyboard typing.
//
// If the client is unaware of the text around the cursor, it should not
// issue this request, to signify lack of support to the compositor.
//
// Text is UTF-8 encoded, and should include the cursor position, the
// complete selection and additional characters before and after them.
// There is a maximum length of wayland messages, so text can not be
// longer than 4000 bytes.
//
// Cursor is the byte offset of the cursor within text buffer.
//
// Anchor is the byte offset of the selection anchor within text buffer.
// If there is no selected text, anchor is the same as cursor.
//
// If any preedit text is present, it is replaced with a cursor for the
// purpose of this event.
//
// Values set with this request are double-buffered. They will get applied
// on the next zwp_text_input_v3.commit request, and stay valid until the
// next committed enable or disable request.
//
// The initial state for affected fields is empty, meaning that the text
// input does not support sending surrounding text. If the empty values
// get applied, subsequent attempts to change them may have no effect.
func (i *ZwpTextInputV3) SetSurroundingText(text string, cursor, anchor int32) error {
	const opcode = 3
	textLen := client.PaddedLen(len(text) + 1)
	_reqBufLen := 8 + (4 + textLen) + 4 + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+textLen)], text)
	l += (4 + textLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(cursor))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(anchor))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetTextChangeCause : indicates the cause of surrounding text change
//
// Tells the compositor why the text surrounding the cursor changed.
//
// Whenever the client detects an external change in text, cursor, or
// anchor posision, it must issue this request to the compositor. This
// request is intended to give the input method a chance to update the
// preedit text in an appropriate way, e.g. by removing it when the user
// starts typing with a keyboard.
//
// cause describes the source of the change.
//
// The value set with this request is double-buffered. It must be applied
// and reset to initial at the next zwp_text_input_v3.commit request.
//
// The initial value of cause is input_method.
func (i *ZwpTextInputV3) SetTextChangeCause(cause uint32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(cause))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetContentType : set content purpose and hint
//
// Sets the content purpose and content hint. While the purpose is the
// basic purpose of an input field, the hint flags allow to modify some of
// the behavior.
//
// Values set with this request are double-buffered. They will get applied
// on the next zwp_text_input_v3.commit request.
// Subsequent attempts to update them may have no effect. The values
// remain valid until the next committed enable or disable request.
//
// The initial value for hint is none, and the initial value for purpose
// is normal.
func (i *ZwpTextInputV3) SetContentType(hint, purpose uint32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(hint))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(purpose))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetCursorRectangle : set cursor position
//
// Marks an area around the cursor as a x, y, width, height rectangle in
// surface local coordinates.
//
// Allows the compositor to put a window with word suggestions near the
// cursor, without obstructing the text being input.
//
// If the client is unaware of the position of edited text, it should not
// issue this request, to signify lack of support to the compositor.
//
// Values set with this request are double-buffered. They will get applied
// on the next zwp_text_input_v3.commit request, and stay valid until the
// next committed enable or disable request.
//
// The initial values describing a cursor rectangle are empty. That means
// the text input does not support describing the cursor area. If the
// empty values get applied, subsequent attempts to change them may have
// no effect.
func (i *ZwpTextInputV3) SetCursorRectangle(x, y, width, height int32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Commit : commit state
//
// Atomically applies state changes recently sent to the compositor.
//
// The commit request establishes and updates the state of the client, and
// must be issued after any changes to apply them.
//
// Text input state (enabled status, content purpose, content hint,
// surrounding text and change cause, cursor rectangle) is conceptually
// double-buffered within the context of a text input, i.e. between a
// committed enable request and the following committed enable or disable
// request.
//
// Protocol requests modify the pending state, as opposed to the current
// state in use by the input method. A commit request atomically applies
// all pending state, replacing the current state. After commit, the new
// pending state is as documented for each related request.
//
// Requests are applied in the order of arrival.
//
// Neither current nor pending state are modified unless noted otherwise.
//
// The compositor must count the number of commit requests coming from
// each zwp_text_input_v3 object and use the count as the serial in done
// events.
func (i *ZwpTextInputV3) Commit() error {
	const opcode = 7
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ZwpTextInputV3ChangeCause uint32

// ZwpTextInputV3ChangeCause : text change reason
//
// Reason for the change of surrounding text or cursor posision.
const (
	// ZwpTextInputV3ChangeCauseInputMethod : input method caused the change
	ZwpTextInputV3ChangeCauseInputMethod ZwpTextInputV3ChangeCause = 0
	// ZwpTextInputV3ChangeCauseOther : something else than the input method caused the change
	ZwpTextInputV3ChangeCauseOther ZwpTextInputV3ChangeCause = 1
)

func (e ZwpTextInputV3ChangeCause) Name() string {
	switch e {
	case ZwpTextInputV3ChangeCauseInputMethod:
		return "input_method"
	case ZwpTextInputV3ChangeCauseOther:
		return "other"
	default:
		return ""
	}
}

func (e ZwpTextInputV3ChangeCause) Value() string {
	switch e {
	case ZwpTextInputV3ChangeCauseInputMethod:
		return "0"
	case ZwpTextInputV3ChangeCauseOther:
		return "1"
	default:
		return ""
	}
}

func (e ZwpTextInputV3ChangeCause) String() string {
	return e.Name() + "=" + e.Value()
}

type ZwpTextInputV3ContentHint uint32

// ZwpTextInputV3ContentHint : content hint
//
// Content hint is a bitmask to allow to modify the behavior of the text
// input.
const (
	// ZwpTextInputV3ContentHintNone : no special behavior
	ZwpTextInputV3ContentHintNone ZwpTextInputV3ContentHint = 0x0
	// ZwpTextInputV3ContentHintCompletion : suggest word completions
	ZwpTextInputV3ContentHintCompletion ZwpTextInputV3ContentHint = 0x1
	// ZwpTextInputV3ContentHintSpellcheck : suggest word corrections
	ZwpTextInputV3ContentHintSpellcheck ZwpTextInputV3ContentHint = 0x2
	// ZwpTextInputV3ContentHintAutoCapitalization : switch to uppercase letters at the start of a sentence
	ZwpTextInputV3ContentHintAutoCapitalization ZwpTextInputV3ContentHint = 0x4
	// ZwpTextInputV3ContentHintLowercase : prefer lowercase letters
	ZwpTextInputV3ContentHintLowercase ZwpTextInputV3ContentHint = 0x8
	// ZwpTextInputV3ContentHintUppercase : prefer uppercase letters
	ZwpTextInputV3ContentHintUppercase ZwpTextInputV3ContentHint = 0x10
	// ZwpTextInputV3ContentHintTitlecase : prefer casing for titles and headings (can be language dependent)
	ZwpTextInputV3ContentHintTitlecase ZwpTextInputV3ContentHint = 0x20
	// ZwpTextInputV3ContentHintHiddenText : characters should be hidden
	ZwpTextInputV3ContentHintHiddenText ZwpTextInputV3ContentHint = 0x40
	// ZwpTextInputV3ContentHintSensitiveData : typed text should not be stored
	ZwpTextInputV3ContentHintSensitiveData ZwpTextInputV3ContentHint = 0x80
	// ZwpTextInputV3ContentHintLatin : just Latin characters should be entered
	ZwpTextInputV3ContentHintLatin ZwpTextInputV3ContentHint = 0x100
	// ZwpTextInputV3ContentHintMultiline : the text input is multiline
	ZwpTextInputV3ContentHintMultiline ZwpTextInputV3ContentHint = 0x200
)

func (e ZwpTextInputV3ContentHint) Name() string {
	switch e {
	case ZwpTextInputV3ContentHintNone:
		return "none"
	case ZwpTextInputV3ContentHintCompletion:
		return "completion"
	case ZwpTextInputV3ContentHintSpellcheck:
		return "spellcheck"
	case ZwpTextInputV3ContentHintAutoCapitalization:
		return "auto_capitalization"
	case ZwpTextInputV3ContentHintLowercase:
		return "lowercase"
	case ZwpTextInputV3ContentHintUppercase:
		return "uppercase"
	case ZwpTextInputV3ContentHintTitlecase:
		return "titlecase"
	case ZwpTextInputV3ContentHintHiddenText:
		return "hidden_text"
	case ZwpTextInputV3ContentHintSensitiveData:
		return "sensitive_data"
	case ZwpTextInputV3ContentHintLatin:
		return "latin"
	case ZwpTextInputV3ContentHintMultiline:
		return "multiline"
	default:
		return ""
	}
}

func (e ZwpTextInputV3ContentHint) Value() string {
	switch e {
	case ZwpTextInputV3ContentHintNone:
		return "0x0"
	case ZwpTextInputV3ContentHintCompletion:
		return "0x1"
	case ZwpTextInputV3ContentHintSpellcheck:
		return "0x2"
	case ZwpTextInputV3ContentHintAutoCapitalization:
		return "0x4"
	case ZwpTextInputV3ContentHintLowercase:
		return "0x8"
	case ZwpTextInputV3ContentHintUppercase:
		return "0x10"
	case ZwpTextInputV3ContentHintTitlecase:
		return "0x20"
	case ZwpTextInputV3ContentHintHiddenText:
		return "0x40"
	case ZwpTextInputV3ContentHintSensitiveData:
		return "0x80"
	case ZwpTextInputV3ContentHintLatin:
		return "0x100"
	case ZwpTextInputV3ContentHintMultiline:
		return "0x200"
	default:
		return ""
	}
}

func (e ZwpTextInputV3ContentHint) String() string {
	return e.Name() + "=" + e.Value()
}

type ZwpTextInputV3ContentPurpose uint32

// ZwpTextInputV3ContentPurpose : content purpose
//
// The content purpose allows to specify the primary purpose of a text
// input.
//
// This allows an input method to show special purpose input panels with
// extra characters or to disallow some characters.
const (
	// ZwpTextInputV3ContentPurposeNormal : default input, allowing all characters
	ZwpTextInputV3ContentPurposeNormal ZwpTextInputV3ContentPurpose = 0
	// ZwpTextInputV3ContentPurposeAlpha : allow only alphabetic characters
	ZwpTextInputV3ContentPurposeAlpha ZwpTextInputV3ContentPurpose = 1
	// ZwpTextInputV3ContentPurposeDigits : allow only digits
	ZwpTextInputV3ContentPurposeDigits ZwpTextInputV3ContentPurpose = 2
	// ZwpTextInputV3ContentPurposeNumber : input a number (including decimal separator and sign)
	ZwpTextInputV3ContentPurposeNumber ZwpTextInputV3ContentPurpose = 3
	// ZwpTextInputV3ContentPurposePhone : input a phone number
	ZwpTextInputV3ContentPurposePhone ZwpTextInputV3ContentPurpose = 4
	// ZwpTextInputV3ContentPurposeUrl : input an URL
	ZwpTextInputV3ContentPurposeUrl ZwpTextInputV3ContentPurpose = 5
	// ZwpTextInputV3ContentPurposeEmail : input an email address
	ZwpTextInputV3ContentPurposeEmail ZwpTextInputV3ContentPurpose = 6
	// ZwpTextInputV3ContentPurposeName : input a name of a person
	ZwpTextInputV3ContentPurposeName ZwpTextInputV3ContentPurpose = 7
	// ZwpTextInputV3ContentPurposePassword : input a password (combine with sensitive_data hint)
	ZwpTextInputV3ContentPurposePassword ZwpTextInputV3ContentPurpose = 8
	// ZwpTextInputV3ContentPurposePin : input is a numeric password (combine with sensitive_data hint)
	ZwpTextInputV3ContentPurposePin ZwpTextInputV3ContentPurpose = 9
	// ZwpTextInputV3ContentPurposeDate : input a date
	ZwpTextInputV3ContentPurposeDate ZwpTextInputV3ContentPurpose = 10
	// ZwpTextInputV3ContentPurposeTime : input a time
	ZwpTextInputV3ContentPurposeTime ZwpTextInputV3ContentPurpose = 11
	// ZwpTextInputV3ContentPurposeDatetime : input a date and time
	ZwpTextInputV3ContentPurposeDatetime ZwpTextInputV3ContentPurpose = 12
	// ZwpTextInputV3ContentPurposeTerminal : input for a terminal
	ZwpTextInputV3ContentPurposeTerminal ZwpTextInputV3ContentPurpose = 13
)

func (e ZwpTextInputV3ContentPurpose) Name() string {
	switch e {
	case ZwpTextInputV3ContentPurposeNormal:
		return "normal"
	case ZwpTextInputV3ContentPurposeAlpha:
		return "alpha"
	case ZwpTextInputV3ContentPurposeDigits:
		return "digits"
	case ZwpTextInputV3ContentPurposeNumber:
		return "number"
	case ZwpTextInputV3ContentPurposePhone:
		return "phone"
	case ZwpTextInputV3ContentPurposeUrl:
		return "url"
	case ZwpTextInputV3ContentPurposeEmail:
		return "email"
	case ZwpTextInputV3ContentPurposeName:
		return "name"
	case ZwpTextInputV3ContentPurposePassword:
		return "password"
	case ZwpTextInputV3ContentPurposePin:
		return "pin"
	case ZwpTextInputV3ContentPurposeDate:
		return "date"
	case ZwpTextInputV3ContentPurposeTime:
		return "time"
	case ZwpTextInputV3ContentPurposeDatetime:
		return "datetime"
	case ZwpTextInputV3ContentPurposeTerminal:
		return "terminal"
	default:
		return ""
	}
}

func (e ZwpTextInputV3ContentPurpose) Value() string {
	switch e {
	case ZwpTextInputV3ContentPurposeNormal:
		return "0"
	case ZwpTextInputV3ContentPurposeAlpha:
		return "1"
	case ZwpTextInputV3ContentPurposeDigits:
		return "2"
	case ZwpTextInputV3ContentPurposeNumber:
		return "3"
	case ZwpTextInputV3ContentPurposePhone:
		return "4"
	case ZwpTextInputV3ContentPurposeUrl:
		return "5"
	case ZwpTextInputV3ContentPurposeEmail:
		return "6"
	case ZwpTextInputV3ContentPurposeName:
		return "7"
	case ZwpTextInputV3ContentPurposePassword:
		return "8"
	case ZwpTextInputV3ContentPurposePin:
		return "9"
	case ZwpTextInputV3ContentPurposeDate:
		return "10"
	case ZwpTextInputV3ContentPurposeTime:
		return "11"
	case ZwpTextInputV3ContentPurposeDatetime:
		return "12"
	case ZwpTextInputV3ContentPurposeTerminal:
		return "13"
	default:
		return ""
	}
}

func (e ZwpTextInputV3ContentPurpose) String() string {
	return e.Name() + "=" + e.Value()
}

// ZwpTextInputV3EnterEvent : enter event
//
// Notification that this seat's text-input focus is on a certain surface.
//
// If client has created multiple text input objects, compositor must send
// this event to all of them.
//
// When the seat has the keyboard capability the text-input focus follows
// the keyboard focus. This event sets the current surface for the
// text-input object.
type ZwpTextInputV3EnterEvent struct {
	Surface *client.Surface
}
type ZwpTextInputV3EnterHandlerFunc func(ZwpTextInputV3EnterEvent)

// SetEnterHandler : sets handler for ZwpTextInputV3EnterEvent
func (i *ZwpTextInputV3) SetEnterHandler(f ZwpTextInputV3EnterHandlerFunc) {
	i.enterHandler = f
}

// ZwpTextInputV3LeaveEvent : leave event
//
// Notification that this seat's text-input focus is no longer on a
// certain surface. The client should reset any preedit string previously
// set.
//
// The leave notification clears the current surface. It is sent before
// the enter notification for the new focus. After leave event, compositor
// must ignore requests from any text input instances until next enter
// event.
//
// When the seat has the keyboard capability the text-input focus follows
// the keyboard focus.
type ZwpTextInputV3LeaveEvent struct {
	Surface *client.Surface
}
type ZwpTextInputV3LeaveHandlerFunc func(ZwpTextInputV3LeaveEvent)

// SetLeaveHandler : sets handler for ZwpTextInputV3LeaveEvent
func (i *ZwpTextInputV3) SetLeaveHandler(f ZwpTextInputV3LeaveHandlerFunc) {
	i.leaveHandler = f
}

// ZwpTextInputV3PreeditStringEvent : pre-edit
//
// Notify when a new composing text (pre-edit) should be set at the
// current cursor position. Any previously set composing text must be
// removed. Any previously existing selected text must be removed.
//
// The argument text contains the pre-edit string buffer.
//
// The parameters cursor_begin and cursor_end are counted in bytes
// relative to the beginning of the submitted text buffer. Cursor should
// be hidden when both are equal to -1.
//
// They could be represented by the client as a line if both values are
// the same, or as a text highlight otherwise.
//
// Values set with this event are double-buffered. They must be applied
// and reset to initial on the next zwp_text_input_v3.done event.
//
// The initial value of text is an empty string, and cursor_begin,
// cursor_end and cursor_hidden are all 0.
type ZwpTextInputV3PreeditStringEvent struct {
	Text        string
	CursorBegin int32
	CursorEnd   int32
}
type ZwpTextInputV3PreeditStringHandlerFunc func(ZwpTextInputV3PreeditStringEvent)

// SetPreeditStringHandler : sets handler for ZwpTextInputV3PreeditStringEvent
func (i *ZwpTextInputV3) SetPreeditStringHandler(f ZwpTextInputV3PreeditStringHandlerFunc) {
	i.preeditStringHandler = f
}

// ZwpTextInputV3CommitStringEvent : text commit
//
// Notify when text should be inserted into the editor widget. The text to
// commit could be either just a single character after a key press or the
// result of some composing (pre-edit).
//
// Values set with this event are double-buffered. They must be applied
// and reset to initial on the next zwp_text_input_v3.done event.
//
// The initial value of text is an empty string.
type ZwpTextInputV3CommitStringEvent struct {
	Text string
}
type ZwpTextInputV3CommitStringHandlerFunc func(ZwpTextInputV3CommitStringEvent)

// SetCommitStringHandler : sets handler for ZwpTextInputV3CommitStringEvent
func (i *ZwpTextInputV3) SetCommitStringHandler(f ZwpTextInputV3CommitStringHandlerFunc) {
	i.commitStringHandler = f
}

// ZwpTextInputV3DeleteSurroundingTextEvent : delete surrounding text
//
// Notify when the text around the current cursor position should be
// deleted.
//
// Before_length and after_length are the number of bytes before and after
// the current cursor index (excluding the selection) to delete.
//
// If a preedit text is present, in effect before_length is counted from
// the beginning of it, and after_length from its end (see done event
// sequence).
//
// Values set with this event are double-buffered. They must be applied
// and reset to initial on the next zwp_text_input_v3.done event.
//
// The initial values of both before_length and after_length are 0.
type ZwpTextInputV3DeleteSurroundingTextEvent struct {
	BeforeLength uint32
	AfterLength  uint32
}
type ZwpTextInputV3DeleteSurroundingTextHandlerFunc func(ZwpTextInputV3DeleteSurroundingTextEvent)

// SetDeleteSurroundingTextHandler : sets handler for ZwpTextInputV3DeleteSurroundingTextEvent
func (i *ZwpTextInputV3) SetDeleteSurroundingTextHandler(f ZwpTextInputV3DeleteSurroundingTextHandlerFunc) {
	i.deleteSurroundingTextHandler = f
}

// ZwpTextInputV3DoneEvent : apply changes
//
// Instruct the application to apply changes to state requested by the
// preedit_string, commit_string and delete_surrounding_text events. The
// state relating to these events is double-buffered, and each one
// modifies the pending state. This event replaces the current state with
// the pending state.
//
// The application must proceed by evaluating the changes in the following
// order:
//
// 1. Replace existing preedit string with the cursor.
// 2. Delete requested surrounding text.
// 3. Insert commit string with the cursor at its end.
// 4. Calculate surrounding text to send.
// 5. Insert new preedit text in cursor position.
// 6. Place cursor inside preedit text.
//
// The serial number reflects the last state of the zwp_text_input_v3
// object known to the compositor. The value of the serial argument must
// be equal to the number of commit requests already issued on that object.
//
// When the client receives a done event with a serial different than the
// number of past commit requests, it must proceed with evaluating and
// applying the changes as normal, except it should not change the current
// state of the zwp_text_input_v3 object. All pending state requests
// (set_surrounding_text, set_content_type and set_cursor_rectangle) on
// the zwp_text_input_v3 object should be sent and committed after
// receiving a zwp_text_input_v3.done event with a matching serial.
type ZwpTextInputV3DoneEvent struct {
	Serial uint32
}
type ZwpTextInputV3DoneHandlerFunc func(ZwpTextInputV3DoneEvent)

// SetDoneHandler : sets handler for ZwpTextInputV3DoneEvent
func (i *ZwpTextInputV3) SetDoneHandler(f ZwpTextInputV3DoneHandlerFunc) {
	i.doneHandler = f
}

func (i *ZwpTextInputV3) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.enterHandler == nil {
			return
		}
		var e ZwpTextInputV3EnterEvent
		l := 0
		surfaceID := client.Uint32(data[l : l+4])
		if surface, ok := i.Context().GetProxy(surfaceID).(*client.Surface); ok && !surface.IsZombie() {
			e.Surface = surface
		} else {
			e.Surface = nil
		}
		l += 4

		i.enterHandler(e)
	case 1:
		if i.leaveHandler == nil {
			return
		}
		var e ZwpTextInputV3LeaveEvent
		l := 0
		surfaceID := client.Uint32(data[l : l+4])
		if surface, ok := i.Context().GetProxy(surfaceID).(*client.Surface); ok && !surface.IsZombie() {
			e.Surface = surface
		} else {
			e.Surface = nil
		}
		l += 4

		i.leaveHandler(e)
	case 2:
		if i.preeditStringHandler == nil {
			return
		}
		var e ZwpTextInputV3PreeditStringEvent
		l := 0
		textLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Text = client.String(data[l : l+textLen])
		l += textLen
		e.CursorBegin = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.CursorEnd = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.preeditStringHandler(e)
	case 3:
		if i.commitStringHandler == nil {
			return
		}
		var e ZwpTextInputV3CommitStringEvent
		l := 0
		textLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Text = client.String(data[l : l+textLen])
		l += textLen

		i.commitStringHandler(e)
	case 4:
		if i.deleteSurroundingTextHandler == nil {
			return
		}
		var e ZwpTextInputV3DeleteSurroundingTextEvent
		l := 0
		e.BeforeLength = client.Uint32(data[l : l+4])
		l += 4
		e.AfterLength = client.Uint32(data[l : l+4])
		l += 4

		i.deleteSurroundingTextHandler(e)
	case 5:
		if i.doneHandler == nil {
			return
		}
		var e ZwpTextInputV3DoneEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4

		i.doneHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}

// ZwpTextInputManagerV3InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const ZwpTextInputManagerV3InterfaceName = "zwp_text_input_manager_v3"

// ZwpTextInputManagerV3 : text input manager
//
// A factory for text-input objects. This object is a global singleton.
type ZwpTextInputManagerV3 struct {
	client.BaseProxy
}

// NewZwpTextInputManagerV3 : text input manager
//
// A factory for text-input objects. This object is a global singleton.
func NewZwpTextInputManagerV3(ctx *client.Context) *ZwpTextInputManagerV3 {
	zwpTextInputManagerV3 := &ZwpTextInputManagerV3{}
	ctx.Register(zwpTextInputManagerV3)
	return zwpTextInputManagerV3
}

// Destroy : Destroy the wp_text_input_manager
//
// Destroy the wp_text_input_manager object.
func (i *ZwpTextInputManagerV3) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetTextInput : create a new text input object
//
// Creates a new text-input object for a given seat.
func (i *ZwpTextInputManagerV3) GetTextInput(seat *client.Seat) (*ZwpTextInputV3, error) {
	id := NewZwpTextInputV3(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}
